import { VECTOR_ARCADE_SAMPLE_FLOW_IDS, VECTOR_ARCADE_SAMPLE_HIGHSCORE_AUTO_EXIT_SECONDS, createVECTORARCADESAMPLEFlowDescriptor } from "../rules/flowRules.js";
import { VECTOR_ARCADE_SAMPLE_FLOW_LABELS, VECTOR_ARCADE_SAMPLE_HIGHSCORE_STATUS } from "../rules/flowContent.js";

export const VECTOR_ARCADE_SAMPLE_HIGHSCORE_FLOW_NEXT_ID = VECTOR_ARCADE_SAMPLE_FLOW_IDS.attract;

export const highscoreFlow = createVECTORARCADESAMPLEFlowDescriptor(VECTOR_ARCADE_SAMPLE_FLOW_IDS.highscore, {
  label: VECTOR_ARCADE_SAMPLE_FLOW_LABELS.highscore,
  nextFlowId: VECTOR_ARCADE_SAMPLE_HIGHSCORE_FLOW_NEXT_ID,
  autoAdvanceSeconds: VECTOR_ARCADE_SAMPLE_HIGHSCORE_AUTO_EXIT_SECONDS,
  statusText: VECTOR_ARCADE_SAMPLE_HIGHSCORE_STATUS
});

