import {
  VECTOR_ARCADE_SAMPLE_FLOW_IDS,
  VECTOR_ARCADE_SAMPLE_FLOW_LABELS,
  VECTOR_ARCADE_SAMPLE_GAME_OVER_AUTO_EXIT_SECONDS,
  VECTOR_ARCADE_SAMPLE_GAME_OVER_RETURN_MODE,
  VECTOR_ARCADE_SAMPLE_GAME_OVER_RETURN_RESET_IDLE,
  VECTOR_ARCADE_SAMPLE_GAME_OVER_RETURN_STATUS,
  createVECTORARCADESAMPLEFlowDescriptor
} from "../rules/gameFlowRules.js";

export const VECTOR_ARCADE_SAMPLE_INTRO_FLOW_NEXT_ID = VECTOR_ARCADE_SAMPLE_FLOW_IDS.highscore;

export const introFlow = createVECTORARCADESAMPLEFlowDescriptor(VECTOR_ARCADE_SAMPLE_FLOW_IDS.intro, {
  label: VECTOR_ARCADE_SAMPLE_FLOW_LABELS.intro,
  nextFlowId: VECTOR_ARCADE_SAMPLE_INTRO_FLOW_NEXT_ID,
  autoAdvanceSeconds: VECTOR_ARCADE_SAMPLE_GAME_OVER_AUTO_EXIT_SECONDS,
  statusText: VECTOR_ARCADE_SAMPLE_GAME_OVER_RETURN_STATUS,
  returnMode: VECTOR_ARCADE_SAMPLE_GAME_OVER_RETURN_MODE,
  resetIdleOnReturn: VECTOR_ARCADE_SAMPLE_GAME_OVER_RETURN_RESET_IDLE
});
