const TOOL_NAME_SUFFIX_PATTERN = /(?:^|[\s_-])(v2|v3|new|final|copy)(?:$|[\s_-])/i;

export const TOOL_REGISTRY = Object.freeze([
  {
    "id": "ai-assistant",
    "name": "AI Assistant",
    "displayName": "AI Assistant",
    "shortDescription": "Get guided technical help for game creation workflows.",
    "shortLabel": "AI Assistant",
    "path": "ai-assistant",
    "folderName": "ai-assistant",
    "entryPoint": "ai-assistant/index.html",
    "description": "Get guided technical help for game creation workflows.",
    "category": "Create",
    "colorGroup": "tool-group-create",
    "requiredForPlayable": false,
    "requiredForTestable": false,
    "requiredForPublish": false,
    "status": "ready",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 1,
    "visibleInToolsList": true
  },
  {
    "id": "project-workspace",
    "name": "Project Workspace",
    "displayName": "Project Workspace",
    "shortDescription": "Coordinate Build, Play, and Share readiness for one game project.",
    "shortLabel": "Project Workspace",
    "path": "project-workspace",
    "folderName": "project-workspace",
    "entryPoint": "project-workspace/index.html",
    "description": "Coordinate Build, Play, and Share readiness for one game project.",
    "category": "Build",
    "colorGroup": "tool-group-build",
    "requiredForPlayable": true,
    "requiredForTestable": true,
    "requiredForPublish": true,
    "status": "in-progress",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 2,
    "visibleInToolsList": true
  },
  {
    "id": "game-design",
    "name": "Game Design",
    "displayName": "Game Design",
    "shortDescription": "Plan gameplay, systems, rules, and player experience.",
    "shortLabel": "Game Design",
    "path": "game-design",
    "folderName": "game-design",
    "entryPoint": "game-design/index.html",
    "description": "Plan gameplay, systems, rules, and player experience.",
    "category": "Build",
    "colorGroup": "tool-group-build",
    "requiredForPlayable": true,
    "requiredForTestable": true,
    "requiredForPublish": true,
    "status": "in-progress",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 3,
    "visibleInToolsList": true
  },
  {
    "id": "game-configuration",
    "name": "Game Configuration",
    "displayName": "Game Configuration",
    "shortDescription": "Plan release profile, debug visibility, and playable readiness gates.",
    "shortLabel": "Game Configuration",
    "path": "game-configuration",
    "folderName": "game-configuration",
    "entryPoint": "game-configuration/index.html",
    "description": "Plan release profile, debug visibility, and playable readiness gates.",
    "category": "Build",
    "colorGroup": "tool-group-build",
    "requiredForPlayable": true,
    "requiredForTestable": true,
    "requiredForPublish": true,
    "status": "ready",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 4,
    "visibleInToolsList": true
  },
  {
    "id": "assets",
    "name": "Assets",
    "displayName": "Assets",
    "shortDescription": "Create sprites, animations, vectors, and palettes.",
    "shortLabel": "Assets",
    "path": "assets",
    "folderName": "assets",
    "entryPoint": "assets/index.html",
    "description": "Create sprites, animations, vectors, and palettes.",
    "category": "Content",
    "colorGroup": "tool-group-content",
    "requiredForPlayable": true,
    "requiredForTestable": true,
    "requiredForPublish": true,
    "status": "in-progress",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 5,
    "visibleInToolsList": true
  },
  {
    "id": "colors",
    "name": "Colors",
    "displayName": "Colors",
    "shortDescription": "Craft and manage color palettes for your games.",
    "shortLabel": "Colors",
    "path": "colors",
    "folderName": "colors",
    "entryPoint": "colors/index.html",
    "description": "Craft and manage color palettes for your games.",
    "category": "Content",
    "colorGroup": "tool-group-content",
    "requiredForPlayable": true,
    "requiredForTestable": true,
    "requiredForPublish": true,
    "status": "complete",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 6,
    "visibleInToolsList": true
  },
  {
    "id": "fonts",
    "name": "Fonts",
    "displayName": "Fonts",
    "shortDescription": "Plan game typography, font loading, and readable text choices.",
    "shortLabel": "Fonts",
    "path": "fonts",
    "folderName": "fonts",
    "entryPoint": "fonts/index.html",
    "description": "Plan game typography, font loading, and readable text choices.",
    "category": "Content",
    "colorGroup": "tool-group-content",
    "requiredForPlayable": false,
    "requiredForTestable": false,
    "requiredForPublish": true,
    "status": "ready",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 7,
    "visibleInToolsList": true
  },
  {
    "id": "sprites",
    "name": "Sprites",
    "displayName": "Sprites",
    "shortDescription": "Plan sprite creation, review, and game-ready export workflows.",
    "shortLabel": "Sprites",
    "path": "sprites",
    "folderName": "sprites",
    "entryPoint": "sprites/index.html",
    "description": "Plan sprite creation, review, and game-ready export workflows.",
    "category": "Content",
    "colorGroup": "tool-group-content",
    "requiredForPlayable": true,
    "requiredForTestable": true,
    "requiredForPublish": true,
    "status": "ready",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 8,
    "visibleInToolsList": true
  },
  {
    "id": "characters",
    "name": "Characters",
    "displayName": "Characters",
    "shortDescription": "Plan player, NPC, and character asset workflows.",
    "shortLabel": "Characters",
    "path": "characters",
    "folderName": "characters",
    "entryPoint": "characters/index.html",
    "description": "Plan player, NPC, and character asset workflows.",
    "category": "Create",
    "colorGroup": "tool-group-create",
    "requiredForPlayable": true,
    "requiredForTestable": true,
    "requiredForPublish": true,
    "status": "ready",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 9,
    "visibleInToolsList": true
  },
  {
    "id": "objects",
    "name": "Objects",
    "displayName": "Objects",
    "shortDescription": "Design reusable game objects and object-ready assets.",
    "shortLabel": "Objects",
    "path": "objects",
    "folderName": "objects",
    "entryPoint": "objects/index.html",
    "description": "Design reusable game objects and object-ready assets.",
    "category": "Create",
    "colorGroup": "tool-group-create",
    "requiredForPlayable": true,
    "requiredForTestable": true,
    "requiredForPublish": true,
    "status": "ready",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 10,
    "visibleInToolsList": true
  },
  {
    "id": "worlds",
    "name": "Worlds",
    "displayName": "Worlds",
    "shortDescription": "Shape world layouts, maps, terrain, and scene geometry.",
    "shortLabel": "Worlds",
    "path": "worlds",
    "folderName": "worlds",
    "entryPoint": "worlds/index.html",
    "description": "Shape world layouts, maps, terrain, and scene geometry.",
    "category": "Create",
    "colorGroup": "tool-group-create",
    "requiredForPlayable": true,
    "requiredForTestable": true,
    "requiredForPublish": true,
    "status": "in-progress",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 11,
    "visibleInToolsList": true
  },
  {
    "id": "animations",
    "name": "Animations",
    "displayName": "Animations",
    "shortDescription": "Plan character and object animation states.",
    "shortLabel": "Animations",
    "path": "animations",
    "folderName": "animations",
    "entryPoint": "animations/index.html",
    "description": "Plan character and object animation states.",
    "category": "Create",
    "colorGroup": "tool-group-create",
    "requiredForPlayable": true,
    "requiredForTestable": true,
    "requiredForPublish": false,
    "status": "in-progress",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 12,
    "visibleInToolsList": true
  },
  {
    "id": "audio",
    "name": "Audio",
    "displayName": "Audio",
    "shortDescription": "Plan game audio, effects, and playback readiness.",
    "shortLabel": "Audio",
    "path": "audio",
    "folderName": "audio",
    "entryPoint": "audio/index.html",
    "description": "Plan game audio, effects, and playback readiness.",
    "category": "Media",
    "colorGroup": "tool-group-media",
    "requiredForPlayable": false,
    "requiredForTestable": false,
    "requiredForPublish": false,
    "status": "ready",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 13,
    "visibleInToolsList": true
  },
  {
    "id": "music",
    "name": "Music",
    "displayName": "Music",
    "shortDescription": "Plan reusable music and soundtrack workflows.",
    "shortLabel": "Music",
    "path": "music",
    "folderName": "music",
    "entryPoint": "music/index.html",
    "description": "Plan reusable music and soundtrack workflows.",
    "category": "Media",
    "colorGroup": "tool-group-media",
    "requiredForPlayable": false,
    "requiredForTestable": false,
    "requiredForPublish": false,
    "status": "ready",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 14,
    "visibleInToolsList": true
  },
  {
    "id": "voices",
    "name": "Voices",
    "displayName": "Voices",
    "shortDescription": "Plan character voice, spoken output, and voice review workflows.",
    "shortLabel": "Voices",
    "path": "voices",
    "folderName": "voices",
    "entryPoint": "voices/index.html",
    "description": "Plan character voice, spoken output, and voice review workflows.",
    "category": "Media",
    "colorGroup": "tool-group-media",
    "requiredForPlayable": false,
    "requiredForTestable": false,
    "requiredForPublish": false,
    "status": "ready",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 15,
    "visibleInToolsList": true
  },
  {
    "id": "videos",
    "name": "Videos",
    "displayName": "Videos",
    "shortDescription": "Plan trailer, cutscene, and video asset workflows.",
    "shortLabel": "Videos",
    "path": "videos",
    "folderName": "videos",
    "entryPoint": "videos/index.html",
    "description": "Plan trailer, cutscene, and video asset workflows.",
    "category": "Media",
    "colorGroup": "tool-group-media",
    "requiredForPlayable": false,
    "requiredForTestable": false,
    "requiredForPublish": false,
    "status": "ready",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 16,
    "visibleInToolsList": true
  },
  {
    "id": "build-game",
    "name": "Build Game",
    "displayName": "Build Game",
    "shortDescription": "Plan build packaging and playable output readiness.",
    "shortLabel": "Build Game",
    "path": "build-game",
    "folderName": "build-game",
    "entryPoint": "build-game/index.html",
    "description": "Plan build packaging and playable output readiness.",
    "category": "Build",
    "colorGroup": "tool-group-build",
    "requiredForPlayable": true,
    "requiredForTestable": true,
    "requiredForPublish": true,
    "status": "locked",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 17,
    "visibleInToolsList": true
  },
  {
    "id": "game-testing",
    "name": "Game Testing",
    "displayName": "Game Testing",
    "shortDescription": "Plan test passes, release checks, and playable validation.",
    "shortLabel": "Game Testing",
    "path": "game-testing",
    "folderName": "game-testing",
    "entryPoint": "game-testing/index.html",
    "description": "Plan test passes, release checks, and playable validation.",
    "category": "Test",
    "colorGroup": "tool-group-test",
    "requiredForPlayable": true,
    "requiredForTestable": true,
    "requiredForPublish": true,
    "status": "locked",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 18,
    "visibleInToolsList": true
  },
  {
    "id": "controls",
    "name": "Controls",
    "displayName": "Controls",
    "shortDescription": "Map keyboard, mouse, gamepad, and touch controls.",
    "shortLabel": "Controls",
    "path": "controls",
    "folderName": "controls",
    "entryPoint": "controls/index.html",
    "description": "Map keyboard, mouse, gamepad, and touch controls.",
    "category": "Test",
    "colorGroup": "tool-group-test",
    "requiredForPlayable": true,
    "requiredForTestable": true,
    "requiredForPublish": true,
    "status": "ready",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 19,
    "visibleInToolsList": true
  },
  {
    "id": "hitboxes",
    "name": "Hitboxes",
    "displayName": "Hitboxes",
    "shortDescription": "Plan collision, hurtbox, and interaction region workflows.",
    "shortLabel": "Hitboxes",
    "path": "hitboxes",
    "folderName": "hitboxes",
    "entryPoint": "hitboxes/index.html",
    "description": "Plan collision, hurtbox, and interaction region workflows.",
    "category": "Test",
    "colorGroup": "tool-group-test",
    "requiredForPlayable": true,
    "requiredForTestable": true,
    "requiredForPublish": true,
    "status": "ready",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 20,
    "visibleInToolsList": true
  },
  {
    "id": "saved-data",
    "name": "Saved Data",
    "displayName": "Saved Data",
    "shortDescription": "Inspect and manage saves, local storage, and game data.",
    "shortLabel": "Saved Data",
    "path": "saved-data",
    "folderName": "saved-data",
    "entryPoint": "saved-data/index.html",
    "description": "Inspect and manage saves, local storage, and game data.",
    "category": "Account",
    "colorGroup": "tool-group-account",
    "requiredForPlayable": false,
    "requiredForTestable": false,
    "requiredForPublish": false,
    "status": "complete",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 21,
    "visibleInToolsList": true
  },
  {
    "id": "debug",
    "name": "Debug",
    "displayName": "Debug",
    "shortDescription": "Plan visible creator debug settings and release gating.",
    "shortLabel": "Debug",
    "path": "debug",
    "folderName": "debug",
    "entryPoint": "debug/index.html",
    "description": "Plan visible creator debug settings and release gating.",
    "category": "Test",
    "colorGroup": "tool-group-test",
    "requiredForPlayable": true,
    "requiredForTestable": true,
    "requiredForPublish": true,
    "status": "ready",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 22,
    "visibleInToolsList": true
  },
  {
    "id": "performance",
    "name": "Performance",
    "displayName": "Performance",
    "shortDescription": "Plan performance budgets, diagnostics, and readiness checks.",
    "shortLabel": "Performance",
    "path": "performance",
    "folderName": "performance",
    "entryPoint": "performance/index.html",
    "description": "Plan performance budgets, diagnostics, and readiness checks.",
    "category": "Test",
    "colorGroup": "tool-group-test",
    "requiredForPlayable": true,
    "requiredForTestable": true,
    "requiredForPublish": true,
    "status": "ready",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 23,
    "visibleInToolsList": true
  },
  {
    "id": "events",
    "name": "Events",
    "displayName": "Events",
    "shortDescription": "Plan gameplay events, triggers, and state transitions.",
    "shortLabel": "Events",
    "path": "events",
    "folderName": "events",
    "entryPoint": "events/index.html",
    "description": "Plan gameplay events, triggers, and state transitions.",
    "category": "Test",
    "colorGroup": "tool-group-test",
    "requiredForPlayable": true,
    "requiredForTestable": true,
    "requiredForPublish": true,
    "status": "ready",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 24,
    "visibleInToolsList": true
  },
  {
    "id": "publish",
    "name": "Publish",
    "displayName": "Publish",
    "shortDescription": "Prepare publishing workflows and release-ready game packages.",
    "shortLabel": "Publish",
    "path": "publish",
    "folderName": "publish",
    "entryPoint": "publish/index.html",
    "description": "Prepare publishing workflows and release-ready game packages.",
    "category": "Share",
    "colorGroup": "tool-group-share",
    "requiredForPlayable": false,
    "requiredForTestable": false,
    "requiredForPublish": true,
    "status": "locked",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 25,
    "visibleInToolsList": true
  },
  {
    "id": "marketplace",
    "name": "Marketplace",
    "displayName": "Marketplace",
    "shortDescription": "Plan marketplace listing, asset, and discovery workflows.",
    "shortLabel": "Marketplace",
    "path": "marketplace",
    "folderName": "marketplace",
    "entryPoint": "marketplace/index.html",
    "description": "Plan marketplace listing, asset, and discovery workflows.",
    "category": "Share",
    "colorGroup": "tool-group-share",
    "requiredForPlayable": false,
    "requiredForTestable": false,
    "requiredForPublish": false,
    "status": "ready",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 26,
    "visibleInToolsList": true
  },
  {
    "id": "community",
    "name": "Community",
    "displayName": "Community",
    "shortDescription": "Plan creator community, tutorials, sharing, and feedback workflows.",
    "shortLabel": "Community",
    "path": "community",
    "folderName": "community",
    "entryPoint": "community/index.html",
    "description": "Plan creator community, tutorials, sharing, and feedback workflows.",
    "category": "Share",
    "colorGroup": "tool-group-share",
    "requiredForPlayable": false,
    "requiredForTestable": false,
    "requiredForPublish": false,
    "status": "ready",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 27,
    "visibleInToolsList": true
  },
  {
    "id": "languages",
    "name": "Languages",
    "displayName": "Languages",
    "shortDescription": "Plan game language coverage and translation review workflows.",
    "shortLabel": "Languages",
    "path": "languages",
    "folderName": "languages",
    "entryPoint": "languages/index.html",
    "description": "Plan game language coverage and translation review workflows.",
    "category": "Share",
    "colorGroup": "tool-group-share",
    "requiredForPlayable": false,
    "requiredForTestable": false,
    "requiredForPublish": false,
    "status": "ready",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 28,
    "visibleInToolsList": true
  },
  {
    "id": "achievements",
    "name": "Achievements",
    "displayName": "Achievements",
    "shortDescription": "Plan achievement definitions and creator-facing unlock review.",
    "shortLabel": "Achievements",
    "path": "achievements",
    "folderName": "achievements",
    "entryPoint": "achievements/index.html",
    "description": "Plan achievement definitions and creator-facing unlock review.",
    "category": "Account",
    "colorGroup": "tool-group-account",
    "requiredForPlayable": false,
    "requiredForTestable": false,
    "requiredForPublish": false,
    "status": "ready",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 29,
    "visibleInToolsList": true
  },
  {
    "id": "ratings",
    "name": "Ratings",
    "displayName": "Ratings",
    "shortDescription": "Plan player ratings, review signals, and quality feedback.",
    "shortLabel": "Ratings",
    "path": "ratings",
    "folderName": "ratings",
    "entryPoint": "ratings/index.html",
    "description": "Plan player ratings, review signals, and quality feedback.",
    "category": "Account",
    "colorGroup": "tool-group-account",
    "requiredForPlayable": false,
    "requiredForTestable": false,
    "requiredForPublish": false,
    "status": "ready",
    "progressChecklist": [
      "Review readiness",
      "Static wireframe text only"
    ],
    "deferred": false,
    "hidden": false,
    "adminOnly": false,
    "active": true,
    "order": 30,
    "visibleInToolsList": true
  },
  {
    "id": "cloud",
    "name": "Cloud",
    "displayName": "Cloud",
    "shortDescription": "Hidden capability shell for connected storage, sync, and publishing support.",
    "shortLabel": "Cloud",
    "path": "cloud",
    "folderName": "cloud",
    "entryPoint": "cloud/index.html",
    "description": "Hidden capability shell for connected storage, sync, and publishing support.",
    "category": "Share",
    "colorGroup": "tool-group-share",
    "requiredForPlayable": false,
    "requiredForTestable": false,
    "requiredForPublish": false,
    "status": "locked",
    "progressChecklist": [
      "Hidden planned capability",
      "Static wireframe text only"
    ],
    "deferred": true,
    "hidden": true,
    "adminOnly": false,
    "active": true,
    "order": 31,
    "visibleInToolsList": true
  },
  {
    "id": "code",
    "name": "Custom Extensions",
    "displayName": "Custom Extensions",
    "shortDescription": "Hidden capability shell for approved extension hooks and creator-private custom logic.",
    "shortLabel": "Custom Extensions",
    "path": "code",
    "folderName": "code",
    "entryPoint": "code/index.html",
    "description": "Hidden capability shell for approved extension hooks and creator-private custom logic.",
    "category": "Build",
    "colorGroup": "tool-group-build",
    "requiredForPlayable": false,
    "requiredForTestable": false,
    "requiredForPublish": false,
    "status": "locked",
    "progressChecklist": [
      "Hidden planned capability",
      "Static wireframe text only"
    ],
    "deferred": true,
    "hidden": true,
    "adminOnly": false,
    "active": true,
    "order": 32,
    "visibleInToolsList": true
  },
  {
    "id": "midi",
    "name": "MIDI",
    "displayName": "MIDI",
    "shortDescription": "Hidden capability shell for MIDI-driven audio and music interaction flows.",
    "shortLabel": "MIDI",
    "path": "midi",
    "folderName": "midi",
    "entryPoint": "midi/index.html",
    "description": "Hidden capability shell for MIDI-driven audio and music interaction flows.",
    "category": "Media",
    "colorGroup": "tool-group-media",
    "requiredForPlayable": false,
    "requiredForTestable": false,
    "requiredForPublish": false,
    "status": "locked",
    "progressChecklist": [
      "Hidden planned capability",
      "Static wireframe text only"
    ],
    "deferred": true,
    "hidden": true,
    "adminOnly": false,
    "active": true,
    "order": 34,
    "visibleInToolsList": true
  },
  {
    "id": "particles",
    "name": "Particles",
    "displayName": "Particles",
    "shortDescription": "Hidden capability shell for visual effects and particle workflows.",
    "shortLabel": "Particles",
    "path": "particles",
    "folderName": "particles",
    "entryPoint": "particles/index.html",
    "description": "Hidden capability shell for visual effects and particle workflows.",
    "category": "Media",
    "colorGroup": "tool-group-media",
    "requiredForPlayable": false,
    "requiredForTestable": false,
    "requiredForPublish": false,
    "status": "locked",
    "progressChecklist": [
      "Hidden planned capability",
      "Static wireframe text only"
    ],
    "deferred": true,
    "hidden": true,
    "adminOnly": false,
    "active": true,
    "order": 35,
    "visibleInToolsList": true
  },
  {
    "id": "audio-effects",
    "name": "Audio Effects",
    "displayName": "Audio Effects",
    "shortDescription": "Hidden capability shell for reusable game effect audio workflows.",
    "shortLabel": "Audio Effects",
    "path": "audio-effects",
    "folderName": "audio-effects",
    "entryPoint": "audio-effects/index.html",
    "description": "Hidden capability shell for reusable game effect audio workflows.",
    "category": "Media",
    "colorGroup": "tool-group-media",
    "requiredForPlayable": false,
    "requiredForTestable": false,
    "requiredForPublish": false,
    "status": "locked",
    "progressChecklist": [
      "Hidden planned capability",
      "Static wireframe text only"
    ],
    "deferred": true,
    "hidden": true,
    "adminOnly": false,
    "active": true,
    "order": 36,
    "visibleInToolsList": true
  },
  {
    "id": "speech-to-text",
    "name": "Voice Capture",
    "displayName": "Voice Capture",
    "shortDescription": "Hidden capability shell for spoken input and transcription workflows.",
    "shortLabel": "Voice Capture",
    "path": "speech-to-text",
    "folderName": "speech-to-text",
    "entryPoint": "speech-to-text/index.html",
    "description": "Hidden capability shell for spoken input and transcription workflows.",
    "category": "Media",
    "colorGroup": "tool-group-media",
    "requiredForPlayable": false,
    "requiredForTestable": false,
    "requiredForPublish": false,
    "status": "locked",
    "progressChecklist": [
      "Hidden planned capability",
      "Static wireframe text only"
    ],
    "deferred": true,
    "hidden": true,
    "adminOnly": false,
    "active": true,
    "order": 37,
    "visibleInToolsList": true
  },
  {
    "id": "text-to-speech",
    "name": "Voice Output",
    "displayName": "Voice Output",
    "shortDescription": "Hidden capability shell for generated narration and spoken output workflows.",
    "shortLabel": "Voice Output",
    "path": "text-to-speech",
    "folderName": "text-to-speech",
    "entryPoint": "text-to-speech/index.html",
    "description": "Hidden capability shell for generated narration and spoken output workflows.",
    "category": "Media",
    "colorGroup": "tool-group-media",
    "requiredForPlayable": false,
    "requiredForTestable": false,
    "requiredForPublish": false,
    "status": "locked",
    "progressChecklist": [
      "Hidden planned capability",
      "Static wireframe text only"
    ],
    "deferred": true,
    "hidden": true,
    "adminOnly": false,
    "active": true,
    "order": 38,
    "visibleInToolsList": true
  }
]);

export { TOOL_NAME_SUFFIX_PATTERN };

export function resolveToolIdAlias(toolId) {
  const normalizedToolId = typeof toolId === "string" ? toolId.trim() : "";
  return normalizedToolId;
}

export function getToolRegistry() {
  return TOOL_REGISTRY.map((tool) => ({ ...tool }));
}

export function getToolById(toolId) {
  const resolvedToolId = resolveToolIdAlias(toolId);
  return getToolRegistry().find((tool) => tool.id === resolvedToolId) ?? null;
}

export function getActiveToolRegistry() {
  return getToolRegistry()
    .filter((tool) => tool.active === true)
    .sort((left, right) => (left.order ?? Number.MAX_SAFE_INTEGER) - (right.order ?? Number.MAX_SAFE_INTEGER));
}

export function getVisibleActiveToolRegistry() {
  return getActiveToolRegistry().filter((tool) => tool.visibleInToolsList === true);
}
