import {
  SOLAR_SYSTEM_FLOW_IDS,
  SOLAR_SYSTEM_FLOW_LABELS,
  SOLAR_SYSTEM_GAME_OVER_RETURN_MODE,
  SOLAR_SYSTEM_GAME_OVER_RETURN_RESET_IDLE,
  SOLAR_SYSTEM_GAME_OVER_RETURN_STATUS,
  createSOLARSYSTEMFlowDescriptor
} from "../rules/gameFlowRules.js";

export const SOLAR_SYSTEM_ATTRACT_FLOW_NEXT_ID = SOLAR_SYSTEM_FLOW_IDS.intro;

export const attractFlow = createSOLARSYSTEMFlowDescriptor(SOLAR_SYSTEM_FLOW_IDS.attract, {
  label: SOLAR_SYSTEM_FLOW_LABELS.attract,
  nextFlowId: SOLAR_SYSTEM_ATTRACT_FLOW_NEXT_ID,
  autoAdvanceSeconds: null,
  statusText: SOLAR_SYSTEM_GAME_OVER_RETURN_STATUS,
  returnMode: SOLAR_SYSTEM_GAME_OVER_RETURN_MODE,
  resetIdleOnReturn: SOLAR_SYSTEM_GAME_OVER_RETURN_RESET_IDLE
});
