import {
  SOLAR_SYSTEM_FLOW_IDS,
  SOLAR_SYSTEM_FLOW_LABELS,
  SOLAR_SYSTEM_HIGHSCORE_AUTO_EXIT_SECONDS,
  SOLAR_SYSTEM_HIGHSCORE_STATUS,
  createSOLARSYSTEMFlowDescriptor
} from "../rules/gameFlowRules.js";

export const SOLAR_SYSTEM_HIGHSCORE_FLOW_NEXT_ID = SOLAR_SYSTEM_FLOW_IDS.attract;

export const highscoreFlow = createSOLARSYSTEMFlowDescriptor(SOLAR_SYSTEM_FLOW_IDS.highscore, {
  label: SOLAR_SYSTEM_FLOW_LABELS.highscore,
  nextFlowId: SOLAR_SYSTEM_HIGHSCORE_FLOW_NEXT_ID,
  autoAdvanceSeconds: SOLAR_SYSTEM_HIGHSCORE_AUTO_EXIT_SECONDS,
  statusText: SOLAR_SYSTEM_HIGHSCORE_STATUS
});
