import {
  SOLAR_SYSTEM_FLOW_IDS,
  SOLAR_SYSTEM_FLOW_LABELS,
  SOLAR_SYSTEM_GAME_OVER_AUTO_EXIT_SECONDS,
  SOLAR_SYSTEM_GAME_OVER_RETURN_MODE,
  SOLAR_SYSTEM_GAME_OVER_RETURN_RESET_IDLE,
  SOLAR_SYSTEM_GAME_OVER_RETURN_STATUS,
  createSOLARSYSTEMFlowDescriptor
} from "../rules/gameFlowRules.js";

export const SOLAR_SYSTEM_INTRO_FLOW_NEXT_ID = SOLAR_SYSTEM_FLOW_IDS.highscore;

export const introFlow = createSOLARSYSTEMFlowDescriptor(SOLAR_SYSTEM_FLOW_IDS.intro, {
  label: SOLAR_SYSTEM_FLOW_LABELS.intro,
  nextFlowId: SOLAR_SYSTEM_INTRO_FLOW_NEXT_ID,
  autoAdvanceSeconds: SOLAR_SYSTEM_GAME_OVER_AUTO_EXIT_SECONDS,
  statusText: SOLAR_SYSTEM_GAME_OVER_RETURN_STATUS,
  returnMode: SOLAR_SYSTEM_GAME_OVER_RETURN_MODE,
  resetIdleOnReturn: SOLAR_SYSTEM_GAME_OVER_RETURN_RESET_IDLE
});
