import {
  SPACE_DUEL_FLOW_IDS,
  SPACE_DUEL_FLOW_LABELS,
  SPACE_DUEL_GAME_OVER_RETURN_MODE,
  SPACE_DUEL_GAME_OVER_RETURN_RESET_IDLE,
  SPACE_DUEL_GAME_OVER_RETURN_STATUS,
  createSPACEDUELFlowDescriptor
} from "../rules/gameFlowRules.js";

export const SPACE_DUEL_ATTRACT_FLOW_NEXT_ID = SPACE_DUEL_FLOW_IDS.intro;

export const attractFlow = createSPACEDUELFlowDescriptor(SPACE_DUEL_FLOW_IDS.attract, {
  label: SPACE_DUEL_FLOW_LABELS.attract,
  nextFlowId: SPACE_DUEL_ATTRACT_FLOW_NEXT_ID,
  autoAdvanceSeconds: null,
  statusText: SPACE_DUEL_GAME_OVER_RETURN_STATUS,
  returnMode: SPACE_DUEL_GAME_OVER_RETURN_MODE,
  resetIdleOnReturn: SPACE_DUEL_GAME_OVER_RETURN_RESET_IDLE
});
