import { SPACE_DUEL_FLOW_IDS, SPACE_DUEL_GAME_OVER_AUTO_EXIT_SECONDS, SPACE_DUEL_GAME_OVER_RETURN_MODE, SPACE_DUEL_GAME_OVER_RETURN_RESET_IDLE, createSPACEDUELFlowDescriptor } from "../rules/flowRules.js";
import { SPACE_DUEL_FLOW_LABELS, SPACE_DUEL_GAME_OVER_RETURN_STATUS } from "../rules/flowContent.js";

export const SPACE_DUEL_INTRO_FLOW_NEXT_ID = SPACE_DUEL_FLOW_IDS.highscore;

export const introFlow = createSPACEDUELFlowDescriptor(SPACE_DUEL_FLOW_IDS.intro, {
  label: SPACE_DUEL_FLOW_LABELS.intro,
  nextFlowId: SPACE_DUEL_INTRO_FLOW_NEXT_ID,
  autoAdvanceSeconds: SPACE_DUEL_GAME_OVER_AUTO_EXIT_SECONDS,
  statusText: SPACE_DUEL_GAME_OVER_RETURN_STATUS,
  returnMode: SPACE_DUEL_GAME_OVER_RETURN_MODE,
  resetIdleOnReturn: SPACE_DUEL_GAME_OVER_RETURN_RESET_IDLE
});

