-- Game Foundry Studio DEV database DDL
-- Group: Admin
-- Ownership: docs_build/database/ddl/admin.sql
-- Target DEV database: gamefoundry_dev
-- Scope: no active persistent Admin tables exist in the Local DB/server API contract yet.
-- Empty-group note: Admin Site Setup owns explicit server-side setup/reseed entry points; no persistent admin table is active.
