-- Game Foundry Studio DEV database DDL
-- Group: Asset
-- Ownership: docs_build/database/ddl/asset.sql
-- Target DEV database: gamefoundry_dev
-- Scope: executable grouped table DDL for active Local DB/server API migration.
-- Authoritative key values are generated by the server/API layer unless a later DEV-only seed exception explicitly applies.
-- Owned tables: asset_role_definitions, asset_library_items, asset_storage_objects, asset_import_events, asset_validation_items
CREATE TABLE IF NOT EXISTS asset_role_definitions (
    key text PRIMARY KEY,
    "id" text,
    "label" text,
    "storageFolder" text,
    "extensions" jsonb NOT NULL DEFAULT '[]'::jsonb,
    "mimeTypes" jsonb NOT NULL DEFAULT '[]'::jsonb,
    "previewBehavior" text,
    "uploadEnabled" boolean NOT NULL DEFAULT false,
    "inputMode" text,
    "usageRoles" jsonb NOT NULL DEFAULT '[]'::jsonb,
    "maxSizeBytes" integer NOT NULL DEFAULT 0,
    "dbFields" jsonb NOT NULL DEFAULT '[]'::jsonb,
    "validationNeeds" jsonb NOT NULL DEFAULT '[]'::jsonb,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_asset_role_definitions_createdby ON asset_role_definitions ("createdBy");
CREATE INDEX IF NOT EXISTS idx_asset_role_definitions_updatedby ON asset_role_definitions ("updatedBy");

CREATE TABLE IF NOT EXISTS asset_library_items (
    key text PRIMARY KEY,
    "id" text,
    "gameId" text REFERENCES game_workspace_games(key),
    "ownerProjectId" text REFERENCES game_workspace_games(key),
    "ownerUserId" text REFERENCES users(key),
    "assetRole" text,
    "assetRoleLabel" text,
    "assetType" text,
    "description" text,
    "tagKeys" jsonb NOT NULL DEFAULT '[]'::jsonb,
    "name" text,
    "source" text,
    "reference" text,
    "fileName" text,
    "originalName" text,
    "mimeType" text,
    "size" integer NOT NULL DEFAULT 0,
    "checksum" text,
    "storageObjectId" text,
    "storedPath" text,
    "path" text,
    "previewKind" text,
    "role" text,
    "type" text,
    "usage" text,
    "status" text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_asset_library_items_gameid ON asset_library_items ("gameId");
CREATE INDEX IF NOT EXISTS idx_asset_library_items_ownerprojectid ON asset_library_items ("ownerProjectId");
CREATE INDEX IF NOT EXISTS idx_asset_library_items_owneruserid ON asset_library_items ("ownerUserId");
CREATE INDEX IF NOT EXISTS idx_asset_library_items_storageobjectid ON asset_library_items ("storageObjectId");
CREATE INDEX IF NOT EXISTS idx_asset_library_items_createdby ON asset_library_items ("createdBy");
CREATE INDEX IF NOT EXISTS idx_asset_library_items_updatedby ON asset_library_items ("updatedBy");

CREATE TABLE IF NOT EXISTS asset_storage_objects (
    key text PRIMARY KEY,
    "id" text,
    "assetId" text REFERENCES asset_library_items(key),
    "gameId" text REFERENCES game_workspace_games(key),
    "ownerProjectId" text REFERENCES game_workspace_games(key),
    "role" text,
    "originalName" text,
    "storedPath" text,
    "mimeType" text,
    "size" integer NOT NULL DEFAULT 0,
    "checksum" text,
    "status" text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_asset_storage_objects_assetid ON asset_storage_objects ("assetId");
CREATE INDEX IF NOT EXISTS idx_asset_storage_objects_gameid ON asset_storage_objects ("gameId");
CREATE INDEX IF NOT EXISTS idx_asset_storage_objects_ownerprojectid ON asset_storage_objects ("ownerProjectId");
CREATE INDEX IF NOT EXISTS idx_asset_storage_objects_createdby ON asset_storage_objects ("createdBy");
CREATE INDEX IF NOT EXISTS idx_asset_storage_objects_updatedby ON asset_storage_objects ("updatedBy");

CREATE TABLE IF NOT EXISTS asset_import_events (
    key text PRIMARY KEY,
    "id" text,
    "assetId" text REFERENCES asset_library_items(key),
    "gameId" text REFERENCES game_workspace_games(key),
    "fileName" text,
    "mimeType" text,
    "storedPath" text,
    "status" text,
    "type" text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_asset_import_events_assetid ON asset_import_events ("assetId");
CREATE INDEX IF NOT EXISTS idx_asset_import_events_gameid ON asset_import_events ("gameId");
CREATE INDEX IF NOT EXISTS idx_asset_import_events_createdby ON asset_import_events ("createdBy");
CREATE INDEX IF NOT EXISTS idx_asset_import_events_updatedby ON asset_import_events ("updatedBy");

CREATE TABLE IF NOT EXISTS asset_validation_items (
    key text PRIMARY KEY,
    "id" text,
    "gameId" text REFERENCES game_workspace_games(key),
    "field" text,
    "label" text,
    "status" text,
    "action" text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_asset_validation_items_gameid ON asset_validation_items ("gameId");
CREATE INDEX IF NOT EXISTS idx_asset_validation_items_createdby ON asset_validation_items ("createdBy");
CREATE INDEX IF NOT EXISTS idx_asset_validation_items_updatedby ON asset_validation_items ("updatedBy");
