-- Game Foundry Studio DEV database DDL
-- Group: Controls
-- Ownership: docs_build/database/ddl/controls.sql
-- Target DEV database: gamefoundry_dev
-- Scope: executable grouped table DDL for active Local DB/server API migration.
-- Authoritative key values are generated by the server/API layer unless a later DEV-only seed exception explicitly applies.
-- Owned tables: game_input_mappings, player_controller_profiles, player_input_device_selections, input_custom_action_records
CREATE TABLE IF NOT EXISTS game_input_mappings (
    key text PRIMARY KEY,
    "id" text,
    "gameId" text REFERENCES game_workspace_games(key),
    "objectKey" text REFERENCES object_definition_records(key),
    "objectName" text,
    "gameAction" text,
    "gameActionLabel" text,
    "usageLabel" text,
    "normalizedInput" text,
    "inputFamily" text,
    "eventD" boolean NOT NULL DEFAULT false,
    "eventH" boolean NOT NULL DEFAULT false,
    "eventU" boolean NOT NULL DEFAULT false,
    "eventDC" boolean NOT NULL DEFAULT false,
    "eventDrag" boolean NOT NULL DEFAULT false,
    "eventAxis" boolean NOT NULL DEFAULT false,
    "enabled" boolean NOT NULL DEFAULT true,
    "state" text,
    "recordOrder" integer NOT NULL DEFAULT 0,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_game_input_mappings_gameid ON game_input_mappings ("gameId");
CREATE INDEX IF NOT EXISTS idx_game_input_mappings_objectkey ON game_input_mappings ("objectKey");
CREATE INDEX IF NOT EXISTS idx_game_input_mappings_createdby ON game_input_mappings ("createdBy");
CREATE INDEX IF NOT EXISTS idx_game_input_mappings_updatedby ON game_input_mappings ("updatedBy");

CREATE TABLE IF NOT EXISTS player_controller_profiles (
    key text PRIMARY KEY,
    "id" text,
    "playerId" text REFERENCES users(key),
    "deviceType" text,
    "controllerName" text,
    "controllerId" text,
    "profileName" text,
    "inputs" jsonb NOT NULL DEFAULT '[]'::jsonb,
    "inputMappings" jsonb NOT NULL DEFAULT '[]'::jsonb,
    "recordOrder" integer NOT NULL DEFAULT 0,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_player_controller_profiles_playerid ON player_controller_profiles ("playerId");
CREATE INDEX IF NOT EXISTS idx_player_controller_profiles_createdby ON player_controller_profiles ("createdBy");
CREATE INDEX IF NOT EXISTS idx_player_controller_profiles_updatedby ON player_controller_profiles ("updatedBy");

CREATE TABLE IF NOT EXISTS player_input_device_selections (
    key text PRIMARY KEY,
    "id" text,
    "playerId" text REFERENCES users(key),
    "selectionKey" text,
    "selectionType" text,
    "deviceType" text,
    "controllerId" text,
    "profileId" text REFERENCES player_controller_profiles(key),
    "label" text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_player_input_device_selections_playerid ON player_input_device_selections ("playerId");
CREATE INDEX IF NOT EXISTS idx_player_input_device_selections_profileid ON player_input_device_selections ("profileId");
CREATE INDEX IF NOT EXISTS idx_player_input_device_selections_createdby ON player_input_device_selections ("createdBy");
CREATE INDEX IF NOT EXISTS idx_player_input_device_selections_updatedby ON player_input_device_selections ("updatedBy");

CREATE TABLE IF NOT EXISTS input_custom_action_records (
    key text PRIMARY KEY,
    "id" text,
    "gameId" text REFERENCES game_workspace_games(key),
    "label" text,
    "recordOrder" integer NOT NULL DEFAULT 0,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_input_custom_action_records_gameid ON input_custom_action_records ("gameId");
CREATE INDEX IF NOT EXISTS idx_input_custom_action_records_createdby ON input_custom_action_records ("createdBy");
CREATE INDEX IF NOT EXISTS idx_input_custom_action_records_updatedby ON input_custom_action_records ("updatedBy");
