-- Game Foundry Studio DEV database DDL
-- Group: Game Crew
-- Ownership: docs_build/database/ddl/game-crew.sql
-- Target DEV database: gamefoundry_dev
-- Scope: executable grouped table DDL for active API/database migration.
-- Authoritative key values are generated by the server/API layer.
-- Owned tables: project_members

CREATE TABLE IF NOT EXISTS project_members (
    key text PRIMARY KEY,
    "projectKey" text NOT NULL REFERENCES game_workspace_games(key),
    "userKey" text NOT NULL REFERENCES users(key),
    role text NOT NULL,
    status text NOT NULL,
    "invitedBy" text REFERENCES users(key),
    "invitedAt" timestamptz,
    "joinedAt" timestamptz,
    "removedAt" timestamptz,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_project_members_project_user ON project_members ("projectKey", "userKey");
CREATE INDEX IF NOT EXISTS idx_project_members_projectkey ON project_members ("projectKey");
CREATE INDEX IF NOT EXISTS idx_project_members_userkey ON project_members ("userKey");
CREATE INDEX IF NOT EXISTS idx_project_members_createdby ON project_members ("createdBy");
CREATE INDEX IF NOT EXISTS idx_project_members_updatedby ON project_members ("updatedBy");
