-- Game Foundry Studio DEV database DDL
-- Group: Game Design
-- Ownership: docs_build/database/ddl/game-design.sql
-- Target DEV database: gamefoundry_dev
-- Scope: executable grouped table DDL for active Supabase/server API migration.
-- Authoritative key values are generated by the server/API layer unless a later DEV-only seed exception explicitly applies.
-- Owned tables: game_design_documents, game_design_validation_items, game_design_sections, game_design_capability_demos
CREATE TABLE IF NOT EXISTS game_design_documents (
    key text PRIMARY KEY,
    "gameKey" text REFERENCES game_workspace_games(key),
    "title" text,
    "gamePurpose" text,
    "gameType" text,
    "genre" text,
    "playStyle" text,
    "playerMode" text,
    "summary" text,
    "story" text,
    "coreLoop" text,
    "winCondition" text,
    "loseCondition" text,
    "targetAudience" text,
    "designNotes" text,
    "capabilityDemoAuthoring" boolean NOT NULL DEFAULT false,
    "capabilityDemoNotes" text,
    "status" text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

ALTER TABLE game_design_documents ADD COLUMN IF NOT EXISTS "gamePurpose" text;
ALTER TABLE game_design_documents ADD COLUMN IF NOT EXISTS "gameType" text;
ALTER TABLE game_design_documents ADD COLUMN IF NOT EXISTS "genre" text;
ALTER TABLE game_design_documents ADD COLUMN IF NOT EXISTS "playStyle" text;
ALTER TABLE game_design_documents ADD COLUMN IF NOT EXISTS "playerMode" text;
ALTER TABLE game_design_documents ADD COLUMN IF NOT EXISTS "summary" text;
ALTER TABLE game_design_documents ADD COLUMN IF NOT EXISTS "story" text;
ALTER TABLE game_design_documents ADD COLUMN IF NOT EXISTS "coreLoop" text;
ALTER TABLE game_design_documents ADD COLUMN IF NOT EXISTS "winCondition" text;
ALTER TABLE game_design_documents ADD COLUMN IF NOT EXISTS "loseCondition" text;
ALTER TABLE game_design_documents ADD COLUMN IF NOT EXISTS "targetAudience" text;
ALTER TABLE game_design_documents ADD COLUMN IF NOT EXISTS "designNotes" text;
ALTER TABLE game_design_documents ADD COLUMN IF NOT EXISTS "capabilityDemoAuthoring" boolean NOT NULL DEFAULT false;
ALTER TABLE game_design_documents ADD COLUMN IF NOT EXISTS "capabilityDemoNotes" text;

CREATE INDEX IF NOT EXISTS idx_game_design_documents_gamekey ON game_design_documents ("gameKey");
CREATE INDEX IF NOT EXISTS idx_game_design_documents_createdby ON game_design_documents ("createdBy");
CREATE INDEX IF NOT EXISTS idx_game_design_documents_updatedby ON game_design_documents ("updatedBy");

CREATE TABLE IF NOT EXISTS game_design_validation_items (
    key text PRIMARY KEY,
    "gameKey" text REFERENCES game_workspace_games(key),
    "field" text,
    "label" text,
    "status" text,
    "action" text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

ALTER TABLE game_design_validation_items ADD COLUMN IF NOT EXISTS "field" text;

CREATE INDEX IF NOT EXISTS idx_game_design_validation_items_gamekey ON game_design_validation_items ("gameKey");
CREATE INDEX IF NOT EXISTS idx_game_design_validation_items_createdby ON game_design_validation_items ("createdBy");
CREATE INDEX IF NOT EXISTS idx_game_design_validation_items_updatedby ON game_design_validation_items ("updatedBy");

CREATE TABLE IF NOT EXISTS game_design_sections (
    key text PRIMARY KEY,
    "gameKey" text REFERENCES game_workspace_games(key),
    "documentKey" text REFERENCES game_design_documents(key),
    "sectionKey" text,
    "heading" text,
    "body" text,
    "sortOrder" integer NOT NULL DEFAULT 0,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_game_design_sections_gamekey ON game_design_sections ("gameKey");
CREATE INDEX IF NOT EXISTS idx_game_design_sections_documentkey ON game_design_sections ("documentKey");
CREATE INDEX IF NOT EXISTS idx_game_design_sections_createdby ON game_design_sections ("createdBy");
CREATE INDEX IF NOT EXISTS idx_game_design_sections_updatedby ON game_design_sections ("updatedBy");

CREATE TABLE IF NOT EXISTS game_design_capability_demos (
    key text PRIMARY KEY,
    "gameKey" text REFERENCES game_workspace_games(key),
    "gameName" text,
    "gamePurpose" text,
    "authoringMode" text,
    "status" text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_game_design_capability_demos_gamekey ON game_design_capability_demos ("gameKey");
CREATE INDEX IF NOT EXISTS idx_game_design_capability_demos_createdby ON game_design_capability_demos ("createdBy");
CREATE INDEX IF NOT EXISTS idx_game_design_capability_demos_updatedby ON game_design_capability_demos ("updatedBy");
