-- Game Foundry Studio DEV database DDL
-- Group: Game Workspace
-- Ownership: docs_build/database/ddl/game-workspace.sql
-- Target DEV database: gamefoundry_dev
-- Scope: executable grouped table DDL for active Supabase/server API migration.
-- Authoritative key values are generated by the server/API layer unless a later DEV-only seed exception explicitly applies.
-- Owned tables: game_workspace_games, game_workspace_progress
CREATE TABLE IF NOT EXISTS game_workspace_games (
    key text PRIMARY KEY,
    "name" text,
    "status" text,
    "ownerKey" text REFERENCES users(key),
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_game_workspace_games_ownerkey ON game_workspace_games ("ownerKey");
CREATE INDEX IF NOT EXISTS idx_game_workspace_games_createdby ON game_workspace_games ("createdBy");
CREATE INDEX IF NOT EXISTS idx_game_workspace_games_updatedby ON game_workspace_games ("updatedBy");

CREATE TABLE IF NOT EXISTS game_workspace_progress (
    key text PRIMARY KEY,
    "gameKey" text REFERENCES game_workspace_games(key),
    "currentFocus" text,
    "gameProgress" text,
    "publishingProgress" text,
    "recommendedNextTool" text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_game_workspace_progress_gamekey ON game_workspace_progress ("gameKey");
CREATE INDEX IF NOT EXISTS idx_game_workspace_progress_createdby ON game_workspace_progress ("createdBy");
CREATE INDEX IF NOT EXISTS idx_game_workspace_progress_updatedby ON game_workspace_progress ("updatedBy");
