-- Game Foundry Studio DEV database DDL
-- Group: Game Journey
-- Ownership: docs_build/database/ddl/game-journey.sql
-- Target DEV database: gamefoundry_dev
-- Scope: executable grouped table DDL for active Supabase/server API migration.
-- Authoritative key values are generated by the server/API layer unless a later DEV-only seed exception explicitly applies.
-- Owned tables: game_journey_completion_metrics, game_journey_note_types, game_journey_notes, game_journey_templates, game_journey_items, game_journey_activity
CREATE TABLE IF NOT EXISTS game_journey_completion_metrics (
    key text PRIMARY KEY,
    "bucketKey" text NOT NULL UNIQUE,
    "bucketOrder" integer NOT NULL DEFAULT 0,
    "bucketName" text NOT NULL,
    "friendlyDescription" text NOT NULL,
    "requiredForMvp" boolean NOT NULL DEFAULT false,
    "canSkip" boolean NOT NULL DEFAULT false,
    "plannedCount" integer NOT NULL DEFAULT 0,
    "completedCount" integer NOT NULL DEFAULT 0,
    "active" boolean NOT NULL DEFAULT true,
    "status" text NOT NULL DEFAULT 'active',
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_game_journey_completion_metrics_active ON game_journey_completion_metrics ("active");
CREATE INDEX IF NOT EXISTS idx_game_journey_completion_metrics_status ON game_journey_completion_metrics ("status");
CREATE INDEX IF NOT EXISTS idx_game_journey_completion_metrics_createdby ON game_journey_completion_metrics ("createdBy");
CREATE INDEX IF NOT EXISTS idx_game_journey_completion_metrics_updatedby ON game_journey_completion_metrics ("updatedBy");

CREATE TABLE IF NOT EXISTS game_journey_note_types (
    key text PRIMARY KEY,
    "typeSlug" text,
    "name" text,
    "seeded" boolean NOT NULL DEFAULT false,
    "userExtensible" boolean NOT NULL DEFAULT false,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_game_journey_note_types_createdby ON game_journey_note_types ("createdBy");
CREATE INDEX IF NOT EXISTS idx_game_journey_note_types_updatedby ON game_journey_note_types ("updatedBy");

CREATE TABLE IF NOT EXISTS game_journey_notes (
    key text PRIMARY KEY,
    "slug" text,
    "gameKey" text REFERENCES game_workspace_games(key),
    "ownerKey" text REFERENCES users(key),
    "name" text,
    "typeKey" text REFERENCES game_journey_note_types(key),
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_game_journey_notes_gamekey ON game_journey_notes ("gameKey");
CREATE INDEX IF NOT EXISTS idx_game_journey_notes_ownerkey ON game_journey_notes ("ownerKey");
CREATE INDEX IF NOT EXISTS idx_game_journey_notes_typekey ON game_journey_notes ("typeKey");
CREATE INDEX IF NOT EXISTS idx_game_journey_notes_createdby ON game_journey_notes ("createdBy");
CREATE INDEX IF NOT EXISTS idx_game_journey_notes_updatedby ON game_journey_notes ("updatedBy");

CREATE TABLE IF NOT EXISTS game_journey_templates (
    key text PRIMARY KEY,
    "templateSlug" text,
    "originalMeaning" text,
    "systemGuidance" text,
    "linkedToolContexts" jsonb NOT NULL DEFAULT '[]'::jsonb,
    "version" integer NOT NULL DEFAULT 0,
    "isActive" boolean NOT NULL DEFAULT true,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_game_journey_templates_createdby ON game_journey_templates ("createdBy");
CREATE INDEX IF NOT EXISTS idx_game_journey_templates_updatedby ON game_journey_templates ("updatedBy");

CREATE TABLE IF NOT EXISTS game_journey_items (
    key text PRIMARY KEY,
    "gameKey" text REFERENCES game_workspace_games(key),
    "noteKey" text REFERENCES game_journey_notes(key),
    "status" text,
    "title" text,
    "userDetails" text,
    "templateKey" text REFERENCES game_journey_templates(key),
    "linkedRecordType" text,
    "linkedRecordId" text,
    "indent" integer NOT NULL DEFAULT 0,
    "order" integer NOT NULL DEFAULT 0,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_game_journey_items_gamekey ON game_journey_items ("gameKey");
CREATE INDEX IF NOT EXISTS idx_game_journey_items_notekey ON game_journey_items ("noteKey");
CREATE INDEX IF NOT EXISTS idx_game_journey_items_templatekey ON game_journey_items ("templateKey");
CREATE INDEX IF NOT EXISTS idx_game_journey_items_createdby ON game_journey_items ("createdBy");
CREATE INDEX IF NOT EXISTS idx_game_journey_items_updatedby ON game_journey_items ("updatedBy");

CREATE TABLE IF NOT EXISTS game_journey_activity (
    key text PRIMARY KEY,
    "gameKey" text REFERENCES game_workspace_games(key),
    "noteKey" text REFERENCES game_journey_notes(key),
    "message" text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_game_journey_activity_gamekey ON game_journey_activity ("gameKey");
CREATE INDEX IF NOT EXISTS idx_game_journey_activity_notekey ON game_journey_activity ("noteKey");
CREATE INDEX IF NOT EXISTS idx_game_journey_activity_createdby ON game_journey_activity ("createdBy");
CREATE INDEX IF NOT EXISTS idx_game_journey_activity_updatedby ON game_journey_activity ("updatedBy");
