-- Game Foundry Studio DEV database DDL
-- Group: Messages
-- Ownership: docs_build/database/ddl/messages.sql
-- Target DEV database: gamefoundry_dev
-- Scope: executable grouped table DDL for active server API migration.
-- Authoritative key values are generated by the server/API layer unless a later DEV-only seed exception explicitly applies.
-- Owned tables: messages_categories, messages_emotion_profiles, messages_records
CREATE TABLE IF NOT EXISTS messages_categories (
    key text PRIMARY KEY,
    "name" text NOT NULL UNIQUE,
    "active" boolean NOT NULL DEFAULT true,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE TABLE IF NOT EXISTS messages_emotion_profiles (
    key text PRIMARY KEY,
    "name" text NOT NULL UNIQUE,
    "description" text NOT NULL DEFAULT '',
    "volume" numeric NOT NULL DEFAULT 1,
    "pitch" numeric NOT NULL DEFAULT 1,
    "rate" numeric NOT NULL DEFAULT 1,
    "pauseBeforeMs" integer NOT NULL DEFAULT 0,
    "pauseAfterMs" integer NOT NULL DEFAULT 0,
    "active" boolean NOT NULL DEFAULT true,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE TABLE IF NOT EXISTS messages_records (
    key text PRIMARY KEY,
    "name" text NOT NULL,
    "categoryKey" text NOT NULL REFERENCES messages_categories(key),
    "emotionProfileKey" text NOT NULL REFERENCES messages_emotion_profiles(key),
    "messageText" text NOT NULL,
    "notes" text NOT NULL DEFAULT '',
    "active" boolean NOT NULL DEFAULT true,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_messages_records_categorykey ON messages_records ("categoryKey");
CREATE INDEX IF NOT EXISTS idx_messages_records_emotionprofilekey ON messages_records ("emotionProfileKey");
CREATE INDEX IF NOT EXISTS idx_messages_records_createdby ON messages_records ("createdBy");
CREATE INDEX IF NOT EXISTS idx_messages_records_updatedby ON messages_records ("updatedBy");
