-- Game Foundry Studio DEV database DDL
-- Group: Messages
-- Ownership: docs_build/database/ddl/messages.sql
-- Target DEV database: gamefoundry_dev
-- Scope: executable grouped table DDL for active server API migration.
-- Authoritative key values are generated by the server/API layer unless a later DEV-only seed exception explicitly applies.
-- Owned tables: messages_categories, messages_emotion_profiles, messages_tts_profiles, messages_records, messages_segments
CREATE TABLE IF NOT EXISTS messages_categories (
    key text PRIMARY KEY,
    "name" text NOT NULL UNIQUE,
    "active" boolean NOT NULL DEFAULT true,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE TABLE IF NOT EXISTS messages_emotion_profiles (
    key text PRIMARY KEY,
    "name" text NOT NULL UNIQUE,
    "description" text NOT NULL DEFAULT '',
    "volume" numeric NOT NULL DEFAULT 1,
    "pitch" numeric NOT NULL DEFAULT 1,
    "rate" numeric NOT NULL DEFAULT 1,
    "pauseBeforeMs" integer NOT NULL DEFAULT 0,
    "pauseAfterMs" integer NOT NULL DEFAULT 0,
    "active" boolean NOT NULL DEFAULT true,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE TABLE IF NOT EXISTS messages_records (
    key text PRIMARY KEY,
    "name" text NOT NULL,
    "categoryKey" text NOT NULL REFERENCES messages_categories(key),
    "emotionProfileKey" text NOT NULL REFERENCES messages_emotion_profiles(key),
    "messageText" text NOT NULL,
    "notes" text NOT NULL DEFAULT '',
    "active" boolean NOT NULL DEFAULT true,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE TABLE IF NOT EXISTS messages_tts_profiles (
    key text PRIMARY KEY,
    "name" text NOT NULL UNIQUE,
    "description" text NOT NULL DEFAULT '',
    "providerKey" text NOT NULL,
    "voiceName" text NOT NULL DEFAULT '',
    "language" text NOT NULL,
    "volume" numeric NOT NULL DEFAULT 1,
    "pitch" numeric NOT NULL DEFAULT 1,
    "rate" numeric NOT NULL DEFAULT 1,
    "active" boolean NOT NULL DEFAULT true,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE TABLE IF NOT EXISTS messages_segments (
    key text PRIMARY KEY,
    "messageKey" text NOT NULL REFERENCES messages_records(key),
    "emotionProfileKey" text NOT NULL REFERENCES messages_emotion_profiles(key),
    "segmentText" text NOT NULL,
    "displayOrder" integer NOT NULL,
    "active" boolean NOT NULL DEFAULT true,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_messages_records_categorykey ON messages_records ("categoryKey");
CREATE INDEX IF NOT EXISTS idx_messages_records_emotionprofilekey ON messages_records ("emotionProfileKey");
CREATE INDEX IF NOT EXISTS idx_messages_records_createdby ON messages_records ("createdBy");
CREATE INDEX IF NOT EXISTS idx_messages_records_updatedby ON messages_records ("updatedBy");
CREATE INDEX IF NOT EXISTS idx_messages_segments_messagekey ON messages_segments ("messageKey");
CREATE INDEX IF NOT EXISTS idx_messages_segments_emotionprofilekey ON messages_segments ("emotionProfileKey");
CREATE INDEX IF NOT EXISTS idx_messages_segments_order ON messages_segments ("messageKey", "displayOrder");
CREATE INDEX IF NOT EXISTS idx_messages_segments_createdby ON messages_segments ("createdBy");
CREATE INDEX IF NOT EXISTS idx_messages_segments_updatedby ON messages_segments ("updatedBy");
CREATE INDEX IF NOT EXISTS idx_messages_tts_profiles_providerkey ON messages_tts_profiles ("providerKey");
CREATE INDEX IF NOT EXISTS idx_messages_tts_profiles_createdby ON messages_tts_profiles ("createdBy");
CREATE INDEX IF NOT EXISTS idx_messages_tts_profiles_updatedby ON messages_tts_profiles ("updatedBy");
