-- Game Foundry Studio DEV database DDL
-- Group: Objects
-- Ownership: docs_build/database/ddl/objects.sql
-- Target DEV database: gamefoundry_dev
-- Scope: executable grouped table DDL for active Supabase/server API migration.
-- Authoritative key values are generated by the server/API layer unless a later DEV-only seed exception explicitly applies.
-- Owned tables: object_definition_records
CREATE TABLE IF NOT EXISTS object_definition_records (
    key text PRIMARY KEY,
    "id" text,
    "gameId" text REFERENCES game_workspace_games(key),
    "name" text,
    "type" text,
    "state" text,
    "modelType" text,
    "renderType" text,
    "renderAssetKey" text REFERENCES asset_library_items(key),
    "renderPreviewPath" text,
    "capabilities" jsonb NOT NULL DEFAULT '[]'::jsonb,
    "behavior" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "interaction" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "recordOrder" integer NOT NULL DEFAULT 0,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_object_definition_records_gameid ON object_definition_records ("gameId");
CREATE INDEX IF NOT EXISTS idx_object_definition_records_renderassetkey ON object_definition_records ("renderAssetKey");
CREATE INDEX IF NOT EXISTS idx_object_definition_records_createdby ON object_definition_records ("createdBy");
CREATE INDEX IF NOT EXISTS idx_object_definition_records_updatedby ON object_definition_records ("updatedBy");
