-- Game Foundry Studio DEV database DDL
-- Group: Palette
-- Ownership: docs_build/database/ddl/palette.sql
-- Target DEV database: gamefoundry_dev
-- Scope: executable grouped table DDL for active Supabase/server API migration.
-- Authoritative key values are generated by the server/API layer unless a later DEV-only seed exception explicitly applies.
-- Owned tables: palette_colors, palette_source_swatches, palette_swatch_usages, project_workspace_palette_globals
CREATE TABLE IF NOT EXISTS palette_colors (
    key text PRIMARY KEY,
    "gameId" text REFERENCES game_workspace_games(key),
    "swatchKey" text,
    "hex" text,
    "name" text,
    "source" text,
    "tags" jsonb NOT NULL DEFAULT '[]'::jsonb,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_palette_colors_gameid ON palette_colors ("gameId");
CREATE INDEX IF NOT EXISTS idx_palette_colors_createdby ON palette_colors ("createdBy");
CREATE INDEX IF NOT EXISTS idx_palette_colors_updatedby ON palette_colors ("updatedBy");

CREATE TABLE IF NOT EXISTS palette_source_swatches (
    key text PRIMARY KEY,
    "id" text,
    "swatchKey" text,
    "hex" text,
    "name" text,
    "source" text,
    "sourceLabel" text,
    "tags" jsonb NOT NULL DEFAULT '[]'::jsonb,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_palette_source_swatches_createdby ON palette_source_swatches ("createdBy");
CREATE INDEX IF NOT EXISTS idx_palette_source_swatches_updatedby ON palette_source_swatches ("updatedBy");

CREATE TABLE IF NOT EXISTS palette_swatch_usages (
    key text PRIMARY KEY,
    "id" text,
    "gameId" text REFERENCES game_workspace_games(key),
    "assetId" text REFERENCES asset_library_items(key),
    "swatchHex" text,
    "swatchName" text,
    "swatchKey" text,
    "toolId" text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_palette_swatch_usages_gameid ON palette_swatch_usages ("gameId");
CREATE INDEX IF NOT EXISTS idx_palette_swatch_usages_assetid ON palette_swatch_usages ("assetId");
CREATE INDEX IF NOT EXISTS idx_palette_swatch_usages_toolid ON palette_swatch_usages ("toolId");
CREATE INDEX IF NOT EXISTS idx_palette_swatch_usages_createdby ON palette_swatch_usages ("createdBy");
CREATE INDEX IF NOT EXISTS idx_palette_swatch_usages_updatedby ON palette_swatch_usages ("updatedBy");

CREATE TABLE IF NOT EXISTS project_workspace_palette_globals (
    key text PRIMARY KEY,
    "gameId" text REFERENCES game_workspace_games(key),
    "swatchCount" integer NOT NULL DEFAULT 0,
    "toolKey" text,
    "workspacePath" text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_project_workspace_palette_globals_gameid ON project_workspace_palette_globals ("gameId");
CREATE INDEX IF NOT EXISTS idx_project_workspace_palette_globals_toolkey ON project_workspace_palette_globals ("toolKey");
CREATE INDEX IF NOT EXISTS idx_project_workspace_palette_globals_createdby ON project_workspace_palette_globals ("createdBy");
CREATE INDEX IF NOT EXISTS idx_project_workspace_palette_globals_updatedby ON project_workspace_palette_globals ("updatedBy");
