-- Game Foundry Studio DEV database DDL
-- Group: Support Tickets
-- Ownership: docs_build/database/ddl/support-tickets.sql
-- Target DEV database: gamefoundry_dev
-- Scope: no active persistent Support Tickets tables exist in the Local DB/server API contract yet.
-- Empty-group note: support ticket tables are not active in the Local DB adapter yet.
