-- Game Foundry Studio DEV database DDL
-- Group: Tags
-- Ownership: docs_build/database/ddl/tags.sql
-- Target DEV database: gamefoundry_dev
-- Scope: executable grouped table DDL for active Local DB/server API migration.
-- Authoritative key values are generated by the server/API layer unless a later DEV-only seed exception explicitly applies.
-- Owned tables: workspace_tag_records
CREATE TABLE IF NOT EXISTS workspace_tag_records (
    key text PRIMARY KEY,
    "id" text,
    "gameId" text REFERENCES game_workspace_games(key),
    "name" text,
    "description" text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_workspace_tag_records_gameid ON workspace_tag_records ("gameId");
CREATE INDEX IF NOT EXISTS idx_workspace_tag_records_createdby ON workspace_tag_records ("createdBy");
CREATE INDEX IF NOT EXISTS idx_workspace_tag_records_updatedby ON workspace_tag_records ("updatedBy");
