-- Game Foundry Studio DEV database DDL
-- Group: Toolbox Votes
-- Ownership: docs_build/database/ddl/toolbox-votes.sql
-- Target DEV database: gamefoundry_dev
-- Scope: executable grouped table DDL for active Local DB/server API migration.
-- Authoritative key values are generated by the server/API layer unless a later DEV-only seed exception explicitly applies.
-- Owned tables: toolbox_votes
CREATE TABLE IF NOT EXISTS toolbox_votes (
    key text PRIMARY KEY,
    "toolId" text,
    "userKey" text REFERENCES users(key),
    "direction" text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_toolbox_votes_toolid ON toolbox_votes ("toolId");
CREATE INDEX IF NOT EXISTS idx_toolbox_votes_userkey ON toolbox_votes ("userKey");
CREATE INDEX IF NOT EXISTS idx_toolbox_votes_createdby ON toolbox_votes ("createdBy");
CREATE INDEX IF NOT EXISTS idx_toolbox_votes_updatedby ON toolbox_votes ("updatedBy");
