-- Game Foundry Studio DEV database DDL
-- Group: Tool Metadata
-- Ownership: docs_build/database/ddl/tool-metadata.sql
-- Target DEV database: gamefoundry_dev
-- Scope: executable grouped table DDL for active Local DB/server API migration.
-- Authoritative key values are generated by the server/API layer unless a later DEV-only seed exception explicitly applies.
-- Owned tables: toolbox_tool_metadata
CREATE TABLE IF NOT EXISTS toolbox_tool_metadata (
    key text PRIMARY KEY,
    "toolKey" text,
    "toolName" text,
    "shortLabel" text,
    "shortDescription" text,
    "description" text,
    "group" text,
    "category" text,
    "colorGroup" text,
    "toolboxGroup" text,
    "subgroup" text,
    "path" text,
    "order" integer NOT NULL DEFAULT 0,
    "status" text,
    "badge" text,
    "toolImage" text,
    "active" boolean NOT NULL DEFAULT true,
    "adminOnly" boolean NOT NULL DEFAULT false,
    "hidden" boolean NOT NULL DEFAULT false,
    "deferred" boolean NOT NULL DEFAULT false,
    "visibleInToolsList" boolean NOT NULL DEFAULT false,
    "capabilityLabel" text,
    "childCapabilities" jsonb NOT NULL DEFAULT '[]'::jsonb,
    "requiredRole" text,
    "statusDiagnostic" text,
    "toolId" text,
    "releaseChannel" text,
    "releaseChannelLabel" text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_toolbox_tool_metadata_toolkey ON toolbox_tool_metadata ("toolKey");
CREATE INDEX IF NOT EXISTS idx_toolbox_tool_metadata_toolid ON toolbox_tool_metadata ("toolId");
CREATE INDEX IF NOT EXISTS idx_toolbox_tool_metadata_createdby ON toolbox_tool_metadata ("createdBy");
CREATE INDEX IF NOT EXISTS idx_toolbox_tool_metadata_updatedby ON toolbox_tool_metadata ("updatedBy");
