-- Game Foundry Studio DEV database DDL
-- Group: Tool Planning
-- Ownership: docs_build/database/ddl/tool-planning.sql
-- Target DEV database: gamefoundry_dev
-- Scope: executable grouped table DDL for active Local DB/server API migration.
-- Authoritative key values are generated by the server/API layer unless a later DEV-only seed exception explicitly applies.
-- Owned tables: toolbox_tool_planning
CREATE TABLE IF NOT EXISTS toolbox_tool_planning (
    key text PRIMARY KEY,
    "toolKey" text,
    "readiness" text,
    "requiredForPlayable" boolean NOT NULL DEFAULT false,
    "requiredForTestable" boolean NOT NULL DEFAULT false,
    "requiredForPublish" boolean NOT NULL DEFAULT false,
    "requires" jsonb NOT NULL DEFAULT '[]'::jsonb,
    "progressChecklist" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdBy" text NOT NULL REFERENCES users(key),
    "updatedBy" text NOT NULL REFERENCES users(key)
);

CREATE INDEX IF NOT EXISTS idx_toolbox_tool_planning_toolkey ON toolbox_tool_planning ("toolKey");
CREATE INDEX IF NOT EXISTS idx_toolbox_tool_planning_createdby ON toolbox_tool_planning ("createdBy");
CREATE INDEX IF NOT EXISTS idx_toolbox_tool_planning_updatedby ON toolbox_tool_planning ("updatedBy");
