import {
  PADDLE_INTERCEPT_FLOW_IDS,
  PADDLE_INTERCEPT_FLOW_LABELS,
  PADDLE_INTERCEPT_GAME_OVER_RETURN_MODE,
  PADDLE_INTERCEPT_GAME_OVER_RETURN_RESET_IDLE,
  PADDLE_INTERCEPT_GAME_OVER_RETURN_STATUS,
  createPADDLEINTERCEPTFlowDescriptor
} from "../rules/gameFlowRules.js";

export const PADDLE_INTERCEPT_ATTRACT_FLOW_NEXT_ID = PADDLE_INTERCEPT_FLOW_IDS.intro;

export const attractFlow = createPADDLEINTERCEPTFlowDescriptor(PADDLE_INTERCEPT_FLOW_IDS.attract, {
  label: PADDLE_INTERCEPT_FLOW_LABELS.attract,
  nextFlowId: PADDLE_INTERCEPT_ATTRACT_FLOW_NEXT_ID,
  autoAdvanceSeconds: null,
  statusText: PADDLE_INTERCEPT_GAME_OVER_RETURN_STATUS,
  returnMode: PADDLE_INTERCEPT_GAME_OVER_RETURN_MODE,
  resetIdleOnReturn: PADDLE_INTERCEPT_GAME_OVER_RETURN_RESET_IDLE
});
