import {
  PADDLE_INTERCEPT_FLOW_IDS,
  PADDLE_INTERCEPT_FLOW_LABELS,
  PADDLE_INTERCEPT_HIGHSCORE_AUTO_EXIT_SECONDS,
  PADDLE_INTERCEPT_HIGHSCORE_STATUS,
  createPADDLEINTERCEPTFlowDescriptor
} from "../rules/gameFlowRules.js";

export const PADDLE_INTERCEPT_HIGHSCORE_FLOW_NEXT_ID = PADDLE_INTERCEPT_FLOW_IDS.attract;

export const highscoreFlow = createPADDLEINTERCEPTFlowDescriptor(PADDLE_INTERCEPT_FLOW_IDS.highscore, {
  label: PADDLE_INTERCEPT_FLOW_LABELS.highscore,
  nextFlowId: PADDLE_INTERCEPT_HIGHSCORE_FLOW_NEXT_ID,
  autoAdvanceSeconds: PADDLE_INTERCEPT_HIGHSCORE_AUTO_EXIT_SECONDS,
  statusText: PADDLE_INTERCEPT_HIGHSCORE_STATUS
});
