import {
  PADDLE_INTERCEPT_FLOW_IDS,
  PADDLE_INTERCEPT_FLOW_LABELS,
  PADDLE_INTERCEPT_GAME_OVER_AUTO_EXIT_SECONDS,
  PADDLE_INTERCEPT_GAME_OVER_RETURN_MODE,
  PADDLE_INTERCEPT_GAME_OVER_RETURN_RESET_IDLE,
  PADDLE_INTERCEPT_GAME_OVER_RETURN_STATUS,
  createPADDLEINTERCEPTFlowDescriptor
} from "../rules/gameFlowRules.js";

export const PADDLE_INTERCEPT_INTRO_FLOW_NEXT_ID = PADDLE_INTERCEPT_FLOW_IDS.highscore;

export const introFlow = createPADDLEINTERCEPTFlowDescriptor(PADDLE_INTERCEPT_FLOW_IDS.intro, {
  label: PADDLE_INTERCEPT_FLOW_LABELS.intro,
  nextFlowId: PADDLE_INTERCEPT_INTRO_FLOW_NEXT_ID,
  autoAdvanceSeconds: PADDLE_INTERCEPT_GAME_OVER_AUTO_EXIT_SECONDS,
  statusText: PADDLE_INTERCEPT_GAME_OVER_RETURN_STATUS,
  returnMode: PADDLE_INTERCEPT_GAME_OVER_RETURN_MODE,
  resetIdleOnReturn: PADDLE_INTERCEPT_GAME_OVER_RETURN_RESET_IDLE
});
