import {
  AI_TARGET_DUMMY_FLOW_IDS,
  AI_TARGET_DUMMY_FLOW_LABELS,
  AI_TARGET_DUMMY_GAME_OVER_RETURN_MODE,
  AI_TARGET_DUMMY_GAME_OVER_RETURN_RESET_IDLE,
  AI_TARGET_DUMMY_GAME_OVER_RETURN_STATUS,
  createAITARGETDUMMYFlowDescriptor
} from "../rules/gameFlowRules.js";

export const AI_TARGET_DUMMY_ATTRACT_FLOW_NEXT_ID = AI_TARGET_DUMMY_FLOW_IDS.intro;

export const attractFlow = createAITARGETDUMMYFlowDescriptor(AI_TARGET_DUMMY_FLOW_IDS.attract, {
  label: AI_TARGET_DUMMY_FLOW_LABELS.attract,
  nextFlowId: AI_TARGET_DUMMY_ATTRACT_FLOW_NEXT_ID,
  autoAdvanceSeconds: null,
  statusText: AI_TARGET_DUMMY_GAME_OVER_RETURN_STATUS,
  returnMode: AI_TARGET_DUMMY_GAME_OVER_RETURN_MODE,
  resetIdleOnReturn: AI_TARGET_DUMMY_GAME_OVER_RETURN_RESET_IDLE
});
