import {
  AI_TARGET_DUMMY_FLOW_IDS,
  AI_TARGET_DUMMY_FLOW_LABELS,
  AI_TARGET_DUMMY_HIGHSCORE_AUTO_EXIT_SECONDS,
  AI_TARGET_DUMMY_HIGHSCORE_STATUS,
  createAITARGETDUMMYFlowDescriptor
} from "../rules/gameFlowRules.js";

export const AI_TARGET_DUMMY_HIGHSCORE_FLOW_NEXT_ID = AI_TARGET_DUMMY_FLOW_IDS.attract;

export const highscoreFlow = createAITARGETDUMMYFlowDescriptor(AI_TARGET_DUMMY_FLOW_IDS.highscore, {
  label: AI_TARGET_DUMMY_FLOW_LABELS.highscore,
  nextFlowId: AI_TARGET_DUMMY_HIGHSCORE_FLOW_NEXT_ID,
  autoAdvanceSeconds: AI_TARGET_DUMMY_HIGHSCORE_AUTO_EXIT_SECONDS,
  statusText: AI_TARGET_DUMMY_HIGHSCORE_STATUS
});
