import {
  AI_TARGET_DUMMY_FLOW_IDS,
  AI_TARGET_DUMMY_FLOW_LABELS,
  AI_TARGET_DUMMY_GAME_OVER_AUTO_EXIT_SECONDS,
  AI_TARGET_DUMMY_GAME_OVER_RETURN_MODE,
  AI_TARGET_DUMMY_GAME_OVER_RETURN_RESET_IDLE,
  AI_TARGET_DUMMY_GAME_OVER_RETURN_STATUS,
  createAITARGETDUMMYFlowDescriptor
} from "../rules/gameFlowRules.js";

export const AI_TARGET_DUMMY_INTRO_FLOW_NEXT_ID = AI_TARGET_DUMMY_FLOW_IDS.highscore;

export const introFlow = createAITARGETDUMMYFlowDescriptor(AI_TARGET_DUMMY_FLOW_IDS.intro, {
  label: AI_TARGET_DUMMY_FLOW_LABELS.intro,
  nextFlowId: AI_TARGET_DUMMY_INTRO_FLOW_NEXT_ID,
  autoAdvanceSeconds: AI_TARGET_DUMMY_GAME_OVER_AUTO_EXIT_SECONDS,
  statusText: AI_TARGET_DUMMY_GAME_OVER_RETURN_STATUS,
  returnMode: AI_TARGET_DUMMY_GAME_OVER_RETURN_MODE,
  resetIdleOnReturn: AI_TARGET_DUMMY_GAME_OVER_RETURN_RESET_IDLE
});
