-- Game Foundry Studio DEV database DML / seed review
-- Group: Asset
-- Ownership: docs_build/database/dml/asset.sql
-- Runtime setup/seed operations for this group must run through server-side APIs.
-- Temporary scope: DEV/review artifact only until Admin Site Setup/server seed APIs fully own grouped setup.
-- Browser pages must not directly seed authoritative DB records.
-- Owned tables: asset_role_definitions, asset_library_items, asset_storage_objects, asset_import_events, asset_validation_items

-- DML status: Server-seed-owned.
-- Setup is performed through the Admin-owned server-side seed API.
-- Browser pages must not seed authoritative records.
-- The server/API layer generates all non-user keys.
-- This SQL file intentionally has no direct INSERT statements because direct SQL would bypass key/audit ownership.
-- Direct SQL setup for this group remains deferred until a later migration-runner PR explicitly owns it.
