-- Game Foundry Studio DEV database DML / seed review
-- Group: Controls
-- Ownership: docs_build/database/dml/controls.sql
-- Runtime setup/seed operations for this group must run through server-side APIs.
-- Temporary scope: DEV/review artifact only until Admin Site Setup/server seed APIs fully own grouped setup.
-- Browser pages must not directly seed authoritative DB records.
-- Owned tables: game_input_mappings, player_controller_profiles, player_input_device_selections, input_custom_action_records

-- DML status: Server-seed-owned.
-- Setup is performed through the Admin-owned server-side seed API.
-- Browser pages must not seed authoritative records.
-- The server/API layer generates all non-user keys.
-- This SQL file intentionally has no direct INSERT statements because direct SQL would bypass key/audit ownership.
-- Direct SQL setup for this group remains deferred until a later migration-runner PR explicitly owns it.
