-- Game Foundry Studio DEV database DML / seed review
-- Group: Support Tickets
-- Ownership: docs_build/database/dml/support-tickets.sql
-- Runtime setup/seed operations for this group must run through server-side APIs.
-- Temporary scope: DEV/review artifact only until Admin Site Setup/server seed APIs fully own grouped setup.
-- Browser pages must not directly seed authoritative DB records.
-- Owned tables: none active
-- Note: Support ticket tables are not active in the Local DB adapter yet.

-- DML status: Future/not-yet-owned.
-- No setup is performed for this group yet because there are no active Local DB support ticket tables.
-- Browser pages must not seed authoritative records.
-- The server/API layer generates all non-user keys.
-- This SQL file intentionally has no direct INSERT statements because direct SQL would bypass key/audit ownership.
-- Direct SQL setup and server-side seed ownership remain deferred until a later support-ticket persistence PR explicitly owns them.
