import { BREAKOUT_FLOW_IDS, BREAKOUT_GAME_OVER_AUTO_EXIT_SECONDS, BREAKOUT_GAME_OVER_RETURN_MODE, BREAKOUT_GAME_OVER_RETURN_RESET_IDLE, createFlowDescriptor } from "../rules/flowRules.js";
import { BREAKOUT_FLOW_LABELS, BREAKOUT_GAME_OVER_RETURN_STATUS } from "../rules/flowContent.js";

export const BREAKOUT_INTRO_FLOW_NEXT_ID = BREAKOUT_FLOW_IDS.highscore;

export const introFlow = createFlowDescriptor(BREAKOUT_FLOW_IDS.intro, {
  label: BREAKOUT_FLOW_LABELS.intro,
  nextFlowId: BREAKOUT_INTRO_FLOW_NEXT_ID,
  autoAdvanceSeconds: BREAKOUT_GAME_OVER_AUTO_EXIT_SECONDS,
  statusText: BREAKOUT_GAME_OVER_RETURN_STATUS,
  returnMode: BREAKOUT_GAME_OVER_RETURN_MODE,
  resetIdleOnReturn: BREAKOUT_GAME_OVER_RETURN_RESET_IDLE
});

