import { THRUSTER_FLOW_IDS, THRUSTER_GAME_OVER_AUTO_EXIT_SECONDS, THRUSTER_GAME_OVER_RETURN_MODE, THRUSTER_GAME_OVER_RETURN_RESET_IDLE, createTHRUSTERFlowDescriptor } from "../rules/flowRules.js";
import { THRUSTER_FLOW_LABELS, THRUSTER_GAME_OVER_RETURN_STATUS } from "../rules/flowContent.js";

export const THRUSTER_INTRO_FLOW_NEXT_ID = THRUSTER_FLOW_IDS.highscore;

export const introFlow = createTHRUSTERFlowDescriptor(THRUSTER_FLOW_IDS.intro, {
  label: THRUSTER_FLOW_LABELS.intro,
  nextFlowId: THRUSTER_INTRO_FLOW_NEXT_ID,
  autoAdvanceSeconds: THRUSTER_GAME_OVER_AUTO_EXIT_SECONDS,
  statusText: THRUSTER_GAME_OVER_RETURN_STATUS,
  returnMode: THRUSTER_GAME_OVER_RETURN_MODE,
  resetIdleOnReturn: THRUSTER_GAME_OVER_RETURN_RESET_IDLE
});

