import {
  SPACE_INVADERS_FLOW_IDS,
  SPACE_INVADERS_FLOW_LABELS,
  SPACE_INVADERS_GAME_OVER_RETURN_MODE,
  SPACE_INVADERS_GAME_OVER_RETURN_RESET_IDLE,
  SPACE_INVADERS_GAME_OVER_RETURN_STATUS,
  createSpaceInvadersFlowDescriptor
} from "../rules/gameFlowRules.js";

export const SPACE_INVADERS_ATTRACT_FLOW_NEXT_ID = SPACE_INVADERS_FLOW_IDS.intro;

export const attractFlow = createSpaceInvadersFlowDescriptor(SPACE_INVADERS_FLOW_IDS.attract, {
  label: SPACE_INVADERS_FLOW_LABELS.attract,
  nextFlowId: SPACE_INVADERS_ATTRACT_FLOW_NEXT_ID,
  autoAdvanceSeconds: null,
  statusText: SPACE_INVADERS_GAME_OVER_RETURN_STATUS,
  returnMode: SPACE_INVADERS_GAME_OVER_RETURN_MODE,
  resetIdleOnReturn: SPACE_INVADERS_GAME_OVER_RETURN_RESET_IDLE
});
