import {
  SPACE_INVADERS_FLOW_IDS,
  SPACE_INVADERS_FLOW_LABELS,
  SPACE_INVADERS_GAME_OVER_AUTO_EXIT_SECONDS,
  SPACE_INVADERS_GAME_OVER_RETURN_MODE,
  SPACE_INVADERS_GAME_OVER_RETURN_RESET_IDLE,
  SPACE_INVADERS_GAME_OVER_RETURN_STATUS,
  createSpaceInvadersFlowDescriptor
} from "../rules/gameFlowRules.js";

export const SPACE_INVADERS_INTRO_FLOW_NEXT_ID = SPACE_INVADERS_FLOW_IDS.highscore;

export const introFlow = createSpaceInvadersFlowDescriptor(SPACE_INVADERS_FLOW_IDS.intro, {
  label: SPACE_INVADERS_FLOW_LABELS.intro,
  nextFlowId: SPACE_INVADERS_INTRO_FLOW_NEXT_ID,
  autoAdvanceSeconds: SPACE_INVADERS_GAME_OVER_AUTO_EXIT_SECONDS,
  statusText: SPACE_INVADERS_GAME_OVER_RETURN_STATUS,
  returnMode: SPACE_INVADERS_GAME_OVER_RETURN_MODE,
  resetIdleOnReturn: SPACE_INVADERS_GAME_OVER_RETURN_RESET_IDLE
});
