import {
  PROJECTILE_LAB_FLOW_IDS,
  PROJECTILE_LAB_FLOW_LABELS,
  PROJECTILE_LAB_GAME_OVER_RETURN_MODE,
  PROJECTILE_LAB_GAME_OVER_RETURN_RESET_IDLE,
  PROJECTILE_LAB_GAME_OVER_RETURN_STATUS,
  createFlowDescriptor
} from "../rules/gameFlowRules.js";

export const PROJECTILE_LAB_ATTRACT_FLOW_NEXT_ID = PROJECTILE_LAB_FLOW_IDS.intro;

export const attractFlow = createFlowDescriptor(PROJECTILE_LAB_FLOW_IDS.attract, {
  label: PROJECTILE_LAB_FLOW_LABELS.attract,
  nextFlowId: PROJECTILE_LAB_ATTRACT_FLOW_NEXT_ID,
  autoAdvanceSeconds: null,
  statusText: PROJECTILE_LAB_GAME_OVER_RETURN_STATUS,
  returnMode: PROJECTILE_LAB_GAME_OVER_RETURN_MODE,
  resetIdleOnReturn: PROJECTILE_LAB_GAME_OVER_RETURN_RESET_IDLE
});
