import { PROJECTILE_LAB_FLOW_IDS, PROJECTILE_LAB_GAME_OVER_AUTO_EXIT_SECONDS, PROJECTILE_LAB_GAME_OVER_RETURN_MODE, PROJECTILE_LAB_GAME_OVER_RETURN_RESET_IDLE, createFlowDescriptor } from "../rules/flowRules.js";
import { PROJECTILE_LAB_FLOW_LABELS, PROJECTILE_LAB_GAME_OVER_RETURN_STATUS } from "../rules/flowContent.js";

export const PROJECTILE_LAB_INTRO_FLOW_NEXT_ID = PROJECTILE_LAB_FLOW_IDS.highscore;

export const introFlow = createFlowDescriptor(PROJECTILE_LAB_FLOW_IDS.intro, {
  label: PROJECTILE_LAB_FLOW_LABELS.intro,
  nextFlowId: PROJECTILE_LAB_INTRO_FLOW_NEXT_ID,
  autoAdvanceSeconds: PROJECTILE_LAB_GAME_OVER_AUTO_EXIT_SECONDS,
  statusText: PROJECTILE_LAB_GAME_OVER_RETURN_STATUS,
  returnMode: PROJECTILE_LAB_GAME_OVER_RETURN_MODE,
  resetIdleOnReturn: PROJECTILE_LAB_GAME_OVER_RETURN_RESET_IDLE
});

