import { PACMAN_FULL_AI_FLOW_IDS, PACMAN_FULL_AI_GAME_OVER_RETURN_MODE, PACMAN_FULL_AI_GAME_OVER_RETURN_RESET_IDLE, createPACMANFULLAIFlowDescriptor } from "../rules/flowRules.js";
import { PACMAN_FULL_AI_FLOW_LABELS, PACMAN_FULL_AI_GAME_OVER_RETURN_STATUS } from "../rules/flowContent.js";

export const PACMAN_FULL_AI_ATTRACT_FLOW_NEXT_ID = PACMAN_FULL_AI_FLOW_IDS.intro;

export const attractFlow = createPACMANFULLAIFlowDescriptor(PACMAN_FULL_AI_FLOW_IDS.attract, {
  label: PACMAN_FULL_AI_FLOW_LABELS.attract,
  nextFlowId: PACMAN_FULL_AI_ATTRACT_FLOW_NEXT_ID,
  autoAdvanceSeconds: null,
  statusText: PACMAN_FULL_AI_GAME_OVER_RETURN_STATUS,
  returnMode: PACMAN_FULL_AI_GAME_OVER_RETURN_MODE,
  resetIdleOnReturn: PACMAN_FULL_AI_GAME_OVER_RETURN_RESET_IDLE
});

