import {
  PACMAN_FULL_AI_FLOW_IDS,
  PACMAN_FULL_AI_FLOW_LABELS,
  PACMAN_FULL_AI_GAME_OVER_AUTO_EXIT_SECONDS,
  PACMAN_FULL_AI_GAME_OVER_RETURN_MODE,
  PACMAN_FULL_AI_GAME_OVER_RETURN_RESET_IDLE,
  PACMAN_FULL_AI_GAME_OVER_RETURN_STATUS,
  createPACMANFULLAIFlowDescriptor
} from "../rules/gameFlowRules.js";

export const PACMAN_FULL_AI_INTRO_FLOW_NEXT_ID = PACMAN_FULL_AI_FLOW_IDS.highscore;

export const introFlow = createPACMANFULLAIFlowDescriptor(PACMAN_FULL_AI_FLOW_IDS.intro, {
  label: PACMAN_FULL_AI_FLOW_LABELS.intro,
  nextFlowId: PACMAN_FULL_AI_INTRO_FLOW_NEXT_ID,
  autoAdvanceSeconds: PACMAN_FULL_AI_GAME_OVER_AUTO_EXIT_SECONDS,
  statusText: PACMAN_FULL_AI_GAME_OVER_RETURN_STATUS,
  returnMode: PACMAN_FULL_AI_GAME_OVER_RETURN_MODE,
  resetIdleOnReturn: PACMAN_FULL_AI_GAME_OVER_RETURN_RESET_IDLE
});
