import {
  PACMAN_LITE_FLOW_IDS,
  PACMAN_LITE_FLOW_LABELS,
  PACMAN_LITE_GAME_OVER_AUTO_EXIT_SECONDS,
  PACMAN_LITE_GAME_OVER_RETURN_MODE,
  PACMAN_LITE_GAME_OVER_RETURN_RESET_IDLE,
  PACMAN_LITE_GAME_OVER_RETURN_STATUS,
  createPACMANLITEFlowDescriptor
} from "../rules/gameFlowRules.js";

export const PACMAN_LITE_INTRO_FLOW_NEXT_ID = PACMAN_LITE_FLOW_IDS.highscore;

export const introFlow = createPACMANLITEFlowDescriptor(PACMAN_LITE_FLOW_IDS.intro, {
  label: PACMAN_LITE_FLOW_LABELS.intro,
  nextFlowId: PACMAN_LITE_INTRO_FLOW_NEXT_ID,
  autoAdvanceSeconds: PACMAN_LITE_GAME_OVER_AUTO_EXIT_SECONDS,
  statusText: PACMAN_LITE_GAME_OVER_RETURN_STATUS,
  returnMode: PACMAN_LITE_GAME_OVER_RETURN_MODE,
  resetIdleOnReturn: PACMAN_LITE_GAME_OVER_RETURN_RESET_IDLE
});
