import {
  MULTI_BALL_CHAOS_FLOW_IDS,
  MULTI_BALL_CHAOS_FLOW_LABELS,
  MULTI_BALL_CHAOS_HIGHSCORE_AUTO_EXIT_SECONDS,
  MULTI_BALL_CHAOS_HIGHSCORE_STATUS,
  createMULTIBALLCHAOSFlowDescriptor
} from "../rules/gameFlowRules.js";

export const MULTI_BALL_CHAOS_HIGHSCORE_FLOW_NEXT_ID = MULTI_BALL_CHAOS_FLOW_IDS.attract;

export const highscoreFlow = createMULTIBALLCHAOSFlowDescriptor(MULTI_BALL_CHAOS_FLOW_IDS.highscore, {
  label: MULTI_BALL_CHAOS_FLOW_LABELS.highscore,
  nextFlowId: MULTI_BALL_CHAOS_HIGHSCORE_FLOW_NEXT_ID,
  autoAdvanceSeconds: MULTI_BALL_CHAOS_HIGHSCORE_AUTO_EXIT_SECONDS,
  statusText: MULTI_BALL_CHAOS_HIGHSCORE_STATUS
});
