import {
  MULTI_BALL_CHAOS_FLOW_IDS,
  MULTI_BALL_CHAOS_FLOW_LABELS,
  MULTI_BALL_CHAOS_GAME_OVER_AUTO_EXIT_SECONDS,
  MULTI_BALL_CHAOS_GAME_OVER_RETURN_MODE,
  MULTI_BALL_CHAOS_GAME_OVER_RETURN_RESET_IDLE,
  MULTI_BALL_CHAOS_GAME_OVER_RETURN_STATUS,
  createMULTIBALLCHAOSFlowDescriptor
} from "../rules/gameFlowRules.js";

export const MULTI_BALL_CHAOS_INTRO_FLOW_NEXT_ID = MULTI_BALL_CHAOS_FLOW_IDS.highscore;

export const introFlow = createMULTIBALLCHAOSFlowDescriptor(MULTI_BALL_CHAOS_FLOW_IDS.intro, {
  label: MULTI_BALL_CHAOS_FLOW_LABELS.intro,
  nextFlowId: MULTI_BALL_CHAOS_INTRO_FLOW_NEXT_ID,
  autoAdvanceSeconds: MULTI_BALL_CHAOS_GAME_OVER_AUTO_EXIT_SECONDS,
  statusText: MULTI_BALL_CHAOS_GAME_OVER_RETURN_STATUS,
  returnMode: MULTI_BALL_CHAOS_GAME_OVER_RETURN_MODE,
  resetIdleOnReturn: MULTI_BALL_CHAOS_GAME_OVER_RETURN_RESET_IDLE
});
