export const ASTEROIDS_FLOW_CONTRACT_VERSION = "1";
export const ASTEROIDS_GAME_OVER_AUTO_EXIT_SECONDS = 30;
export const ASTEROIDS_GAME_OVER_RETURN_MODE = "menu";
export const ASTEROIDS_GAME_OVER_RETURN_RESET_IDLE = true;
export const ASTEROIDS_HIGHSCORE_AUTO_EXIT_SECONDS = 12;

