import {
  GRAVITY_WELL_FLOW_IDS,
  GRAVITY_WELL_FLOW_LABELS,
  GRAVITY_WELL_GAME_OVER_AUTO_EXIT_SECONDS,
  GRAVITY_WELL_GAME_OVER_RETURN_MODE,
  GRAVITY_WELL_GAME_OVER_RETURN_RESET_IDLE,
  GRAVITY_WELL_GAME_OVER_RETURN_STATUS,
  createFlowDescriptor
} from "../rules/gameFlowRules.js";

export const GRAVITY_WELL_INTRO_FLOW_NEXT_ID = GRAVITY_WELL_FLOW_IDS.highscore;

export const introFlow = createFlowDescriptor(GRAVITY_WELL_FLOW_IDS.intro, {
  label: GRAVITY_WELL_FLOW_LABELS.intro,
  nextFlowId: GRAVITY_WELL_INTRO_FLOW_NEXT_ID,
  autoAdvanceSeconds: GRAVITY_WELL_GAME_OVER_AUTO_EXIT_SECONDS,
  statusText: GRAVITY_WELL_GAME_OVER_RETURN_STATUS,
  returnMode: GRAVITY_WELL_GAME_OVER_RETURN_MODE,
  resetIdleOnReturn: GRAVITY_WELL_GAME_OVER_RETURN_RESET_IDLE
});
