import { ACTIVE_PROJECT_STORAGE_KEY } from "../shared/projectManifestContract.js";
import {
  createStateInspectorSnapshot,
  safeParseJson,
  toPrettyJson
} from "../shared/debugInspectorData.js";
import { readToolHostSharedContextFromLocation } from "../shared/toolHostSharedContext.js";
import { registerToolBootContract } from "../shared/toolBootContract.js";

const refs = {
  refreshButton: document.getElementById("refreshSnapshotButton"),
  loadJsonButton: document.getElementById("loadJsonButton"),
  statusText: document.getElementById("stateInspectorStatus"),
  input: document.getElementById("stateJsonInput"),
  output: document.getElementById("stateSnapshotOutput")
};

const state = {
  snapshot: null
};

function setStatus(message) {
  if (refs.statusText instanceof HTMLElement) {
    refs.statusText.textContent = message;
  }
}

function readStorageEntries(storageLike, prefix = "") {
  const entries = [];
  if (!storageLike || typeof storageLike.length !== "number") {
    return entries;
  }

  for (let index = 0; index < storageLike.length; index += 1) {
    const key = storageLike.key(index);
    if (!key || (prefix && !key.startsWith(prefix))) {
      continue;
    }
    const value = storageLike.getItem(key);
    entries.push({
      key,
      value: typeof value === "string" ? value : ""
    });
  }

  entries.sort((left, right) => left.key.localeCompare(right.key));
  return entries;
}

function readProjectManifest() {
  try {
    const raw = window.localStorage.getItem(ACTIVE_PROJECT_STORAGE_KEY);
    if (!raw) {
      return null;
    }
    return safeParseJson(raw);
  } catch {
    return null;
  }
}

function readBootRegistryKeys() {
  const registry = globalThis.__TOOLS_BOOT_CONTRACT_REGISTRY__;
  if (!registry || typeof registry !== "object") {
    return [];
  }
  return Object.keys(registry).sort((left, right) => left.localeCompare(right));
}

function buildLiveSnapshot() {
  const hostContext = readToolHostSharedContextFromLocation(window.location);
  const localStorageEntries = readStorageEntries(window.localStorage, "toolboxaid.");
  const sessionStorageEntries = readStorageEntries(window.sessionStorage, "toolboxaid.");
  const hosted = new URLSearchParams(window.location.search).get("hosted") === "1";
  return createStateInspectorSnapshot({
    hosted,
    toolId: "state-inspector",
    hostContext,
    projectManifest: readProjectManifest(),
    localStorageEntries,
    sessionStorageEntries,
    bootRegistryKeys: readBootRegistryKeys(),
    notes: "Read-only snapshot generated by State Inspector."
  });
}

function renderSnapshot(snapshot) {
  state.snapshot = snapshot;
  if (refs.output instanceof HTMLElement) {
    refs.output.textContent = toPrettyJson(snapshot);
  }

  const localCount = snapshot?.storage?.localCount ?? 0;
  const sessionCount = snapshot?.storage?.sessionCount ?? 0;
  const bootCount = snapshot?.bootContracts?.count ?? 0;
  setStatus(`Snapshot ready. local=${localCount}, session=${sessionCount}, bootContracts=${bootCount}.`);
}

function refreshSnapshot() {
  renderSnapshot(buildLiveSnapshot());
}

function inspectInputJson() {
  if (!(refs.input instanceof HTMLTextAreaElement)) {
    return;
  }
  const parsed = safeParseJson(refs.input.value);
  if (!parsed || typeof parsed !== "object") {
    setStatus("Input JSON is invalid. Paste valid JSON to inspect.");
    return;
  }
  renderSnapshot(parsed);
  setStatus("Custom JSON payload loaded into inspector view.");
}

function bindEvents() {
  if (refs.refreshButton instanceof HTMLButtonElement) {
    refs.refreshButton.addEventListener("click", refreshSnapshot);
  }
  if (refs.loadJsonButton instanceof HTMLButtonElement) {
    refs.loadJsonButton.addEventListener("click", inspectInputJson);
  }
}

let initialized = false;

const stateInspectorApi = {
  captureProjectState() {
    return {
      input: refs.input instanceof HTMLTextAreaElement ? refs.input.value : "",
      snapshot: state.snapshot
    };
  },
  applyProjectState(snapshot) {
    if (refs.input instanceof HTMLTextAreaElement && typeof snapshot?.input === "string") {
      refs.input.value = snapshot.input;
    }
    if (snapshot?.snapshot && typeof snapshot.snapshot === "object") {
      renderSnapshot(snapshot.snapshot);
      return true;
    }
    refreshSnapshot();
    return true;
  }
};

function bootStateInspector() {
  if (!initialized) {
    bindEvents();
    refreshSnapshot();
    initialized = true;
  }
  window.stateInspectorApp = stateInspectorApi;
  return stateInspectorApi;
}

registerToolBootContract("state-inspector", {
  init: bootStateInspector,
  destroy() {
    return true;
  },
  getApi() {
    return window.stateInspectorApp || null;
  }
});

bootStateInspector();
