import {
  BOUNCING_BALL_FLOW_IDS,
  BOUNCING_BALL_FLOW_LABELS,
  BOUNCING_BALL_GAME_OVER_AUTO_EXIT_SECONDS,
  BOUNCING_BALL_GAME_OVER_RETURN_MODE,
  BOUNCING_BALL_GAME_OVER_RETURN_RESET_IDLE,
  BOUNCING_BALL_GAME_OVER_RETURN_STATUS,
  createFlowDescriptor
} from "../rules/gameFlowRules.js";

export const BOUNCING_BALL_INTRO_FLOW_NEXT_ID = BOUNCING_BALL_FLOW_IDS.highscore;

export const introFlow = createFlowDescriptor(BOUNCING_BALL_FLOW_IDS.intro, {
  label: BOUNCING_BALL_FLOW_LABELS.intro,
  nextFlowId: BOUNCING_BALL_INTRO_FLOW_NEXT_ID,
  autoAdvanceSeconds: BOUNCING_BALL_GAME_OVER_AUTO_EXIT_SECONDS,
  statusText: BOUNCING_BALL_GAME_OVER_RETURN_STATUS,
  returnMode: BOUNCING_BALL_GAME_OVER_RETURN_MODE,
  resetIdleOnReturn: BOUNCING_BALL_GAME_OVER_RETURN_RESET_IDLE
});
